import type { Course, Question } from "../types";

const Q = (
  id: string,
  topic: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question => ({ id, type: "mcq", topic, question, options, correctIndex, explanation });

const T1 = "Rocks and Soil Formation";
const T2 = "Soil Fertility";
const T3 = "Soil and Water Conservation";
const T4 = "Land Preparation and Tillage";
const T5 = "Soil–Water–Plant Relationship";

const questions: Question[] = [
  // --- Topic 1: Rocks and Soil Formation ---
  Q("agg102_t1_q1", T1, "Which type of rock forms when hot magma cools and solidifies?",
    ["Sedimentary", "Igneous", "Metamorphic", "Organic"], 1,
    "Igneous rocks form from the cooling of molten magma or lava. Examples: granite, basalt."),
  Q("agg102_t1_q2", T1, "Which of these is an example of a metamorphic rock?",
    ["Granite", "Sandstone", "Marble", "Basalt"], 2,
    "Marble and slate are metamorphic rocks, formed under extreme heat and pressure."),
  Q("agg102_t1_q3", T1, "Sedimentary rocks are typically formed by:",
    ["Cooling of magma", "Accumulation and hardening of sand, mud, or shells", "Extreme heat and pressure underground", "Volcanic eruptions only"], 1,
    "Sedimentary rocks form when particles pile up and harden over time — e.g., sandstone, limestone, coal."),
  Q("agg102_t1_q4", T1, "Which of these is NOT an igneous rock?",
    ["Granite", "Basalt", "Limestone", "Obsidian"], 2,
    "Limestone is sedimentary. Granite, basalt, and obsidian are all igneous."),
  Q("agg102_t1_q5", T1, "The CLORPT acronym lists five factors of soil formation. Which is NOT one of them?",
    ["Climate", "Living organisms", "Rainfall", "Parent material"], 2,
    "CLORPT = Climate, Living organisms, Relief, Parent material, Time. Rainfall is covered under Climate."),
  Q("agg102_t1_q6", T1, "In CLORPT, the 'R' stands for:",
    ["Rainfall", "Relief", "Rocks", "Roots"], 1,
    "Relief (topography) — steep land erodes faster and forms shallower soils."),
  Q("agg102_t1_q7", T1, "Chemical weathering occurs when:",
    ["Rocks crack due to heat and cold", "Water and chemicals dissolve or alter rocks", "Roots physically break rocks", "Animals burrow through soil"], 1,
    "Chemical weathering involves reactions such as dissolution, oxidation, and hydrolysis."),
  Q("agg102_t1_q8", T1, "Physical weathering is primarily caused by:",
    ["Acids", "Plant roots", "Heat, cold, and friction", "Bacteria"], 2,
    "Physical weathering is mechanical — temperature changes, freeze–thaw, abrasion."),
  Q("agg102_t1_q9", T1, "Which soil horizon is the dark, nutrient-rich topsoil?",
    ["O", "A", "B", "C"], 1,
    "A horizon is topsoil — rich in organic matter and nutrients."),
  Q("agg102_t1_q10", T1, "The 'R' horizon of a soil profile refers to:",
    ["Roots", "Residue", "Solid bedrock", "Rainfall zone"], 2,
    "R horizon is the solid bedrock at the base of the soil profile."),
  Q("agg102_t1_q11", T1, "Coal is classified as a:",
    ["Igneous rock", "Metamorphic rock", "Sedimentary rock", "Volcanic rock"], 2,
    "Coal forms from compressed plant material — a sedimentary rock."),
  Q("agg102_t1_q12", T1, "Marble is formed from which original rock?",
    ["Granite", "Limestone", "Sandstone", "Basalt"], 1,
    "Marble is metamorphosed limestone."),
  Q("agg102_t1_q13", T1, "Slate is a metamorphic rock formed from:",
    ["Shale/mudstone", "Granite", "Basalt", "Sandstone"], 0,
    "Slate forms from shale under low-grade metamorphism."),
  Q("agg102_t1_q14", T1, "Which factor of soil formation adds organic matter to soil?",
    ["Climate", "Living organisms", "Parent material", "Time"], 1,
    "Plants, animals, and microbes contribute organic matter as they grow, die, and decompose."),
  Q("agg102_t1_q15", T1, "Which soil horizon is known as the leached zone?",
    ["A", "E", "B", "O"], 1,
    "E horizon — nutrients have been washed downward (leached) out of it."),
  Q("agg102_t1_q16", T1, "Biological weathering is caused by:",
    ["Wind", "Temperature changes", "Living organisms", "Chemical reactions"], 2,
    "Roots, burrowing animals, lichens, and microbes break rocks apart physically or chemically."),
  Q("agg102_t1_q17", T1, "Good agricultural soil generally takes how long to form?",
    ["Days", "Weeks", "A few years", "Thousands of years"], 3,
    "Soil formation is a very slow process — often thousands of years."),
  Q("agg102_t1_q18", T1, "Granite is an example of:",
    ["Sedimentary rock", "Metamorphic rock", "Igneous rock", "Biogenic rock"], 2,
    "Granite is a coarse-grained intrusive igneous rock."),
  Q("agg102_t1_q19", T1, "Which horizon consists of partially broken rock above the bedrock?",
    ["B", "C", "E", "O"], 1,
    "C horizon is weathered parent material just above bedrock."),
  Q("agg102_t1_q20", T1, "'Parent material' of a soil refers to:",
    ["Overlying vegetation", "The underlying rock or material from which soil develops", "Leaf litter", "The water table"], 1,
    "Parent material determines the initial minerals and texture of a soil."),
  Q("agg102_t1_q21", T1, "The O horizon is mainly made up of:",
    ["Bedrock", "Subsoil clay", "Dead leaves and organic matter", "Leached minerals"], 2,
    "O horizon is the surface layer of organic debris."),
  Q("agg102_t1_q22", T1, "Which is the correct order of soil horizons from top to bottom?",
    ["O, A, E, B, C, R", "R, C, B, E, A, O", "A, O, B, E, C, R", "O, B, A, C, E, R"], 0,
    "Standard order: O → A → E → B → C → R."),

  // --- Topic 2: Soil Fertility ---
  Q("agg102_t2_q1", T2, "How many essential nutrients do plants need to grow?",
    ["12", "15", "17", "20"], 2,
    "17 essential nutrients, including macro- and micronutrients plus C, H, O."),
  Q("agg102_t2_q2", T2, "Which nutrients do plants obtain directly from air and water?",
    ["N, P, K", "Ca, Mg, S", "C, H, O", "Fe, Zn, Cu"], 2,
    "Carbon, hydrogen, and oxygen come from CO₂ and H₂O."),
  Q("agg102_t2_q3", T2, "The three primary plant nutrients are:",
    ["C, H, O", "N, P, K", "Ca, Mg, S", "Fe, Zn, Cu"], 1,
    "Nitrogen, phosphorus, and potassium are the primary macronutrients."),
  Q("agg102_t2_q4", T2, "Which nutrient primarily supports leaf and stem growth?",
    ["Phosphorus", "Nitrogen", "Potassium", "Calcium"], 1,
    "Nitrogen is central to chlorophyll and protein synthesis — green, leafy growth."),
  Q("agg102_t2_q5", T2, "Purple leaves typically indicate deficiency of:",
    ["Nitrogen", "Phosphorus", "Potassium", "Iron"], 1,
    "Phosphorus deficiency classically produces purplish leaves."),
  Q("agg102_t2_q6", T2, "General yellowing of leaves usually indicates deficiency of:",
    ["Phosphorus", "Nitrogen", "Potassium", "Calcium"], 1,
    "Nitrogen deficiency causes chlorosis (yellowing), usually starting with older leaves."),
  Q("agg102_t2_q7", T2, "Potassium is especially important for:",
    ["Water regulation and disease resistance", "Chlorophyll formation", "Seed oil content", "Nitrogen fixation"], 0,
    "K helps regulate stomata, water use, and enzyme activation."),
  Q("agg102_t2_q8", T2, "Leaf-edge burning (necrosis) typically indicates deficiency of:",
    ["N", "P", "K", "Ca"], 2,
    "Potassium deficiency shows as scorched or burnt leaf margins."),
  Q("agg102_t2_q9", T2, "The best soil pH range for most crops is:",
    ["3.0–4.5", "6.0–7.5", "8.0–9.5", "10.0+"], 1,
    "Slightly acidic to neutral soils (pH 6.0–7.5) suit most crops."),
  Q("agg102_t2_q10", T2, "Below pH 5.5, which element commonly becomes toxic to plants?",
    ["Calcium", "Magnesium", "Aluminium", "Sodium"], 2,
    "Acidic soils release soluble aluminium, which is toxic to roots."),
  Q("agg102_t2_q11", T2, "Micronutrients are needed by plants in:",
    ["Very large amounts", "Moderate amounts", "Very small amounts", "No amount at all"], 2,
    "Micronutrients (Fe, Zn, Cu, B, etc.) are essential but required in trace quantities."),
  Q("agg102_t2_q12", T2, "Which of these is NOT a secondary nutrient?",
    ["Calcium", "Magnesium", "Sulfur", "Iron"], 3,
    "Iron is a micronutrient. Secondary: Ca, Mg, S."),
  Q("agg102_t2_q13", T2, "Which of these is NOT a micronutrient?",
    ["Iron", "Boron", "Zinc", "Nitrogen"], 3,
    "Nitrogen is a primary macronutrient, not a micronutrient."),
  Q("agg102_t2_q14", T2, "A soil can be fertile yet unproductive if it has:",
    ["Flooding or erosion", "High nutrient content", "Balanced pH", "Good structure"], 0,
    "Productivity also depends on physical conditions like drainage and erosion control."),
  Q("agg102_t2_q15", T2, "ISFM stands for:",
    ["Integrated Soil Fertility Management", "International Soil Field Method", "Inorganic Soil Farming Model", "Irrigation Soil Fertility Management"], 0,
    "ISFM combines organic and inorganic inputs for sustainable fertility."),
  Q("agg102_t2_q16", T2, "Which is an organic source of soil fertility?",
    ["Urea", "NPK fertilizer", "Compost", "Superphosphate"], 2,
    "Compost, manure, and crop residues are organic fertility inputs."),
  Q("agg102_t2_q17", T2, "Which of these is an inorganic fertilizer?",
    ["Farmyard manure", "Compost", "Urea", "Crop residues"], 2,
    "Urea is a synthetic (inorganic) nitrogen fertilizer."),
  Q("agg102_t2_q18", T2, "Nitrogen-fixing bacteria contribute to fertility by:",
    ["Converting atmospheric N₂ into plant-usable forms", "Decomposing phosphorus rock", "Neutralising acidic soils", "Binding potassium"], 0,
    "Rhizobia and other N-fixers turn N₂ into ammonia/nitrate available to plants."),
  Q("agg102_t2_q19", T2, "A common fertility problem in many Nigerian soils is:",
    ["Excess organic matter", "Low organic matter and leaching", "Strongly alkaline pH everywhere", "Over-rich phosphorus"], 1,
    "Tropical Nigerian soils often suffer low OM, high leaching, P-fixation, and acidity."),
  Q("agg102_t2_q20", T2, "Soil with pH above 8.0 tends to cause:",
    ["Aluminium toxicity", "Micronutrient shortage", "Nitrogen excess", "Sulfur saturation"], 1,
    "Alkaline soils reduce availability of Fe, Zn, Mn, etc."),
  Q("agg102_t2_q21", T2, "Which property most affects a soil's water-holding ability?",
    ["Texture and structure", "Surface colour", "Smell", "Slope direction"], 0,
    "Texture (sand/silt/clay mix) and structure govern pore space and water retention."),
  Q("agg102_t2_q22", T2, "Earthworms improve fertility mainly by:",
    ["Fixing nitrogen", "Mixing soil and creating channels", "Eating roots", "Raising pH drastically"], 1,
    "Earthworm activity improves aeration, mixing, and organic matter incorporation."),

  // --- Topic 3: Soil and Water Conservation ---
  Q("agg102_t3_q1", T3, "The primary aim of Soil and Water Conservation (SWC) is to:",
    ["Increase chemical use", "Protect soil from erosion and keep water available", "Speed up erosion for nutrient release", "Remove all vegetation"], 1,
    "SWC protects soil and water resources so land remains productive."),
  Q("agg102_t3_q2", T3, "Which of these is a natural cause of soil loss?",
    ["Deforestation", "Overgrazing", "Heavy rain", "Bush burning"], 2,
    "Heavy rain, wind, and steep slopes are natural drivers of erosion."),
  Q("agg102_t3_q3", T3, "Which is a human cause of erosion?",
    ["Heavy rain", "Sandy soil", "Steep slope", "Deforestation"], 3,
    "Clearing vegetation exposes soil and accelerates erosion."),
  Q("agg102_t3_q4", T3, "Gully erosion is especially common in which part of Nigeria?",
    ["Northern", "Southeastern", "Southwestern", "Middle Belt"], 1,
    "Southeastern Nigeria is notorious for severe gully erosion."),
  Q("agg102_t3_q5", T3, "Wind erosion is more common in which part of Nigeria?",
    ["Southwestern", "Northern", "Southeastern", "Niger Delta"], 1,
    "Northern Nigeria's drier climate makes wind erosion more prevalent."),
  Q("agg102_t3_q6", T3, "Which is NOT a type of water erosion?",
    ["Splash", "Sheet", "Gully", "Frost"], 3,
    "Frost is a weathering process, not a water-erosion type. Water types: splash, sheet, rill, gully."),
  Q("agg102_t3_q7", T3, "Contour farming is classified as a/an:",
    ["Agronomic method", "Mechanical structure", "Vegetative method", "Biological control"], 0,
    "Agronomic = crop/management-based practices like contouring, cover crops, mulching."),
  Q("agg102_t3_q8", T3, "Terracing is a/an:",
    ["Agronomic practice", "Mechanical (structural) method", "Vegetative method", "Chemical control"], 1,
    "Terraces are engineered structures that break long slopes into shorter, flatter sections."),
  Q("agg102_t3_q9", T3, "Vetiver grass is primarily used for:",
    ["Food", "Soil conservation / stabilising slopes", "Fuel", "Ornamental beauty only"], 1,
    "Vetiver's deep roots bind soil and slow runoff."),
  Q("agg102_t3_q10", T3, "Zero tillage supports conservation because:",
    ["It deeply ploughs the soil", "It avoids disturbing the soil surface", "It removes all crop residues", "It encourages burning"], 1,
    "No-till keeps residues on top and protects soil structure."),
  Q("agg102_t3_q11", T3, "Mulching primarily helps by:",
    ["Increasing evaporation", "Conserving moisture and reducing erosion", "Adding more weed seeds", "Raising soil pH"], 1,
    "Mulch cuts evaporation, moderates temperature, and shields soil from raindrop impact."),
  Q("agg102_t3_q12", T3, "Gabions are used to:",
    ["Store grain", "Stabilise gullies and stream banks", "Plough land", "Irrigate crops directly"], 1,
    "Gabions are wire cages filled with rocks used for erosion control."),
  Q("agg102_t3_q13", T3, "Which is a vegetative conservation method?",
    ["Terracing", "Contour farming", "Planting windbreaks", "Check dams"], 2,
    "Windbreaks, grass strips, and reforestation are vegetative methods."),
  Q("agg102_t3_q14", T3, "A check dam is primarily for:",
    ["Storing drinking water", "Slowing runoff and trapping sediment in gullies", "Pumping water uphill", "Large-scale irrigation storage"], 1,
    "Small check dams reduce runoff velocity and capture sediment in gully channels."),
  Q("agg102_t3_q15", T3, "Agroforestry combines:",
    ["Only trees", "Only crops", "Trees with crops and/or livestock", "Only herbicide use"], 2,
    "Agroforestry integrates woody perennials with crops or animals on the same land."),
  Q("agg102_t3_q16", T3, "Which water-conservation practice collects rainwater from roofs?",
    ["Farm ponds", "Roof water harvesting", "Deep tillage", "Mulching"], 1,
    "Roof water harvesting channels rainwater from rooftops into storage."),
  Q("agg102_t3_q17", T3, "Sheet erosion is characterised by:",
    ["Deep channels", "Uniform thin removal of topsoil from a wide area", "Major landslides", "Wind-blown dunes"], 1,
    "Sheet erosion quietly strips topsoil in thin layers — often unnoticed until severe."),
  Q("agg102_t3_q18", T3, "Conservation tillage typically leaves at least what percentage of crop residue on the soil?",
    ["10%", "20%", "30%", "50%"], 2,
    "30% residue cover is the standard threshold for 'conservation tillage'."),
  Q("agg102_t3_q19", T3, "Which farming practice plants crops across slopes to slow runoff?",
    ["Bush burning", "Contour farming", "Deep ploughing", "Monocropping"], 1,
    "Contour farming follows the land's natural contours, creating mini-barriers to runoff."),
  Q("agg102_t3_q20", T3, "Reforestation helps conservation mainly by:",
    ["Adding chemicals", "Anchoring soil with roots and reducing runoff", "Removing organic matter", "Raising ambient temperature"], 1,
    "Tree roots bind the soil while canopies intercept rainfall and reduce erosion."),
  Q("agg102_t3_q21", T3, "Crop rotation contributes to SWC by:",
    ["Exhausting soil nutrients faster", "Maintaining soil cover and breaking pest cycles", "Removing organic matter", "Encouraging gullies"], 1,
    "Rotating crops preserves soil structure, nutrients, and reduces pest pressure."),
  Q("agg102_t3_q22", T3, "Splash erosion is caused by:",
    ["Animals grazing", "Direct raindrop impact on bare soil", "Slow-moving streams", "Wind"], 1,
    "Raindrop impact dislodges soil particles, the first stage of water erosion."),

  // --- Topic 4: Land Preparation and Tillage ---
  Q("agg102_t4_q1", T4, "Primary tillage is typically done at what depth?",
    ["1–5 cm", "5–10 cm", "15–30 cm", "50+ cm"], 2,
    "Primary tillage is the initial deep ploughing (~15–30 cm)."),
  Q("agg102_t4_q2", T4, "Harrowing and ridging are examples of:",
    ["Primary tillage", "Secondary tillage", "Tertiary tillage", "Zero tillage"], 1,
    "Secondary tillage refines the seedbed after primary ploughing."),
  Q("agg102_t4_q3", T4, "Intercultural (tertiary) tillage is performed:",
    ["Before planting", "During and after crop establishment", "Only at harvest", "Only in fallow years"], 1,
    "Tertiary tillage includes weeding and cultivating among growing crops."),
  Q("agg102_t4_q4", T4, "Conventional tillage usually involves:",
    ["Only direct seeding", "Full ploughing plus harrowing", "No soil disturbance", "Burning crop residues"], 1,
    "Conventional tillage fully inverts and works the soil."),
  Q("agg102_t4_q5", T4, "Zero tillage often requires:",
    ["Deep ploughs", "Herbicides for weed control", "Only animal traction", "Heavy irrigation"], 1,
    "Because weeds are not mechanically disturbed, herbicides often replace that function."),
  Q("agg102_t4_q6", T4, "Which tillage system leaves at least 30% residue on the surface?",
    ["Conventional", "Minimum", "Conservation", "Deep"], 2,
    "Conservation tillage's defining feature is ≥30% residue cover."),
  Q("agg102_t4_q7", T4, "The main goal of tillage is to:",
    ["Increase erosion", "Create a suitable seedbed", "Remove topsoil", "Kill beneficial microbes"], 1,
    "Good tillage produces a seedbed that supports germination and growth."),
  Q("agg102_t4_q8", T4, "A disadvantage of excessive tillage is:",
    ["Improved structure", "Hardpan formation and lost organic matter", "Higher organic matter", "Lower cost"], 1,
    "Repeated tillage compacts layers and depletes soil OM."),
  Q("agg102_t4_q9", T4, "Animal-drawn tillage typically uses:",
    ["Tractors", "Ox-ploughs", "Disc harrows", "Drones"], 1,
    "Oxen pulling ploughs is a common intermediate technology."),
  Q("agg102_t4_q10", T4, "Mechanised tillage usually uses:",
    ["Hoes", "Tractors and implements", "Ox-ploughs", "Hand tools only"], 1,
    "Tractors with ploughs, harrows, ridgers, etc., are the mechanised option."),
  Q("agg102_t4_q11", T4, "Typical manual tillage tools include:",
    ["Hoe and cutlass", "Tractor and harrow", "Combine harvesters", "Irrigation pumps"], 0,
    "Smallholder farmers commonly use hoes and cutlasses."),
  Q("agg102_t4_q12", T4, "Conservation agriculture emphasises:",
    ["Deep ploughing every season", "Minimum soil disturbance and residue retention", "Burning residues", "Monoculture without rotation"], 1,
    "CA's pillars: minimum disturbance, permanent cover, diversification."),
  Q("agg102_t4_q13", T4, "Precision farming relies heavily on:",
    ["Random guesses", "Data and site-specific inputs", "Bush burning", "Hand tools only"], 1,
    "Precision ag uses sensors, GPS, and data to vary inputs precisely across a field."),
  Q("agg102_t4_q14", T4, "Which is NOT a goal of tillage?",
    ["Weed control", "Mixing fertilizers into the soil", "Compacting soil", "Improving aeration"], 2,
    "Compacting soil is a harmful side-effect, not a goal."),
  Q("agg102_t4_q15", T4, "Hardpan formation is usually caused by:",
    ["Light tillage", "Repeated ploughing at the same depth", "No tillage", "Mulching"], 1,
    "Ploughing to the same depth season after season creates a compacted subsoil layer."),
  Q("agg102_t4_q16", T4, "Minimum tillage aims to:",
    ["Maximise soil disturbance", "Reduce the number of tillage passes", "Remove all residues", "Increase erosion"], 1,
    "Fewer passes, less disturbance, lower cost."),
  Q("agg102_t4_q17", T4, "Which operation typically comes first?",
    ["Harrowing", "Primary ploughing", "Ridging", "Weeding"], 1,
    "Primary ploughing opens and inverts the soil before finer secondary operations."),
  Q("agg102_t4_q18", T4, "Climate-smart tillage aims to:",
    ["Maximise CO₂ emissions", "Protect soil and reduce carbon emissions", "Increase erosion", "Rely mostly on burning"], 1,
    "Climate-smart practices keep carbon in soil and reduce fuel-intensive operations."),
  Q("agg102_t4_q19", T4, "Which method best suits very large farms?",
    ["Manual hoeing", "Ox-plough only", "Mechanised tractor operations", "None of these"], 2,
    "Large-scale farming usually relies on tractors and implements for efficiency."),
  Q("agg102_t4_q20", T4, "A potential disadvantage of zero tillage is:",
    ["It always improves soil structure", "Increased reliance on herbicides", "Guaranteed lower yields", "Loss of biodiversity"], 1,
    "Without mechanical weed control, farmers often use more herbicides."),
  Q("agg102_t4_q21", T4, "Ridging is generally classified under:",
    ["Primary tillage", "Secondary tillage", "Tertiary tillage", "No-till"], 1,
    "Ridging typically refines the seedbed and is considered secondary tillage."),
  Q("agg102_t4_q22", T4, "Excessive tillage tends to do which of the following to organic matter?",
    ["Increase it", "Preserve it", "Decrease it", "Not affect it"], 2,
    "Tillage exposes OM to oxygen, accelerating its decomposition and loss."),

  // --- Topic 5: Soil–Water–Plant Relationship ---
  Q("agg102_t5_q1", T5, "Which form of water is held most tightly to soil particles and unavailable to plants?",
    ["Gravitational", "Capillary", "Hygroscopic", "Free runoff"], 2,
    "Hygroscopic water is adsorbed in extremely thin films — plants cannot access it."),
  Q("agg102_t5_q2", T5, "Which water form is mostly used by plants?",
    ["Gravitational", "Capillary", "Hygroscopic", "Runoff"], 1,
    "Capillary water is held in small pores at tensions plants can extract."),
  Q("agg102_t5_q3", T5, "Gravitational water is best described as:",
    ["Always available to plants", "Water that drains freely after rainfall", "Water bound to soil particles", "Frozen water"], 1,
    "It moves downward under gravity and is mostly not retained for plant use."),
  Q("agg102_t5_q4", T5, "Field Capacity is:",
    ["The driest possible soil state", "Soil moisture after excess water has drained away", "Saturated soil just after rain", "The wilting point"], 1,
    "Field capacity = moisture remaining after gravitational drainage — ideal for growth."),
  Q("agg102_t5_q5", T5, "The Permanent Wilting Point is:",
    ["Soil so dry that plants cannot recover even after watering", "Saturated soil", "Optimal moisture for growth", "A pH measurement"], 0,
    "Beyond PWP, plants wilt irreversibly."),
  Q("agg102_t5_q6", T5, "Available Water Capacity (AWC) equals:",
    ["Field Capacity + Wilting Point", "Field Capacity − Wilting Point", "Saturation − Field Capacity", "Hygroscopic + Capillary"], 1,
    "AWC is the plant-usable water between field capacity and PWP."),
  Q("agg102_t5_q7", T5, "Which soil type holds the MOST water (but may release it slowly)?",
    ["Sand", "Silt", "Clay", "Gravel"], 2,
    "Clay has many tiny pores and high retention, though much of it can be tightly held."),
  Q("agg102_t5_q8", T5, "The best soil texture for balancing retention and drainage is:",
    ["Pure sand", "Pure clay", "Loam", "Gravel"], 2,
    "Loam mixes sand, silt, and clay — holds water yet drains well."),
  Q("agg102_t5_q9", T5, "More organic matter generally:",
    ["Reduces water retention", "Improves water retention and structure", "Causes hardpans", "Only lowers pH"], 1,
    "OM increases aggregation, porosity, and water-holding capacity."),
  Q("agg102_t5_q10", T5, "Infiltration refers to:",
    ["Upward water movement", "Water entering the soil surface", "Water reaching the water table", "Surface runoff"], 1,
    "Infiltration is the entry of water into the soil."),
  Q("agg102_t5_q11", T5, "Percolation refers to:",
    ["Water entering the soil", "Water moving downward through the soil profile", "Water rising upward", "Evaporation"], 1,
    "Percolation is the downward movement of water within the soil."),
  Q("agg102_t5_q12", T5, "Capillary rise describes:",
    ["Downward water movement", "Water moving upward from lower soil layers", "Surface runoff", "Transpiration"], 1,
    "Water moves upward through small pores against gravity."),
  Q("agg102_t5_q13", T5, "Transpiration is water loss from:",
    ["Soil only", "Plant leaves", "Rivers", "Aquifers"], 1,
    "Transpiration is evaporative water loss through stomata on leaves."),
  Q("agg102_t5_q14", T5, "Evapotranspiration (ET) combines:",
    ["Evaporation from soil + transpiration from plants", "Percolation + runoff", "Infiltration + evaporation", "Rain + runoff"], 0,
    "ET = total water loss from the soil–plant system to the atmosphere."),
  Q("agg102_t5_q15", T5, "Water stress in plants commonly causes:",
    ["Increased yield", "Wilting and reduced photosynthesis", "Larger leaves", "Darker stems"], 1,
    "Drought/salinity stress triggers stomatal closure, wilting, and yield loss."),
  Q("agg102_t5_q16", T5, "Closing stomata during drought helps plants to:",
    ["Increase transpiration", "Reduce water loss", "Fix more nitrogen", "Increase photosynthesis"], 1,
    "Stomatal closure conserves water, at the cost of reduced CO₂ uptake."),
  Q("agg102_t5_q17", T5, "Drip irrigation is known for:",
    ["High water loss", "Targeted, highly efficient water use", "Large-scale flooding", "Overhead spray"], 1,
    "Drip delivers water directly to the root zone with minimal loss."),
  Q("agg102_t5_q18", T5, "Sprinkler irrigation most resembles:",
    ["Natural rainfall", "Flood irrigation", "Drip emitters", "Sub-surface wetting"], 0,
    "Sprinklers spray water overhead, mimicking rainfall."),
  Q("agg102_t5_q19", T5, "In tropical soils like Nigeria's, heavy rainfall commonly causes:",
    ["Leaching of nutrients", "Salt buildup", "pH rising above 9", "No erosion"], 0,
    "Heavy rainfall leaches soluble nutrients downward, away from roots."),
  Q("agg102_t5_q20", T5, "Soil crusting typically:",
    ["Improves infiltration", "Blocks water entry into the soil", "Increases yields", "Fixes nitrogen"], 1,
    "A crusted surface seals pores and promotes runoff rather than infiltration."),
  Q("agg102_t5_q21", T5, "Which practice best reduces evaporation from the soil surface?",
    ["Deep ploughing daily", "Mulching", "Removing residues", "Irrigating at noon"], 1,
    "Mulch shades the soil and dramatically reduces surface evaporation."),
  Q("agg102_t5_q22", T5, "Sandy soils primarily differ from clay soils in that they:",
    ["Hold more water", "Drain quickly and hold less water", "Always have higher fertility", "Have no pore space"], 1,
    "Sandy soils have large pores — fast drainage and low retention."),
];

export const AGG_102_SEED: Course = {
  id: "agg102",
  name: "AGG 102 — Introduction to Soil Science",
  description: "Rocks & soil formation, soil fertility, conservation, tillage, and soil–water–plant relationships.",
  createdAt: Date.now(),
  updatedAt: Date.now(),
  questions,
};
