import type { Course, Question } from "../types";

const Q = (
  id: string,
  topic: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question => ({ id, type: "mcq", topic, question, options, correctIndex, explanation });

const T1 = "s-Block Metals (Groups IA & IIA)";
const T2 = "Group IVA & Carbon Allotropes";
const T3 = "Transition Metals & Coordination Compounds";
const T4 = "Sodium, Aluminium & Non-metals";
const T5 = "Benzene & Aromatic Chemistry";
const T6 = "Alcohols, Phenols, Aldehydes & Ketones";
const T7 = "Carboxylic Acids, Derivatives & Amines";
const T8 = "Qualitative Analysis of Salts";
const T9 = "History, Bonding & Nanotechnology";

const questions: Question[] = [
  // --- T1: s-Block Metals ---
  Q("chm102_t1_q1", T1, "The outermost electronic configuration of every alkali metal is:",
    ["ns²", "ns¹", "ns²np¹", "(n-1)d¹ns²"], 1,
    "Alkali metals all have a single loosely-held electron in their outermost s-orbital (ns¹), which is why they easily lose it to form M⁺ ions."),
  Q("chm102_t1_q2", T1, "Which alkali metal gives a crimson red flame?",
    ["Lithium", "Sodium", "Potassium", "Caesium"], 0,
    "Li → crimson red; Na → yellow; K, Rb, Cs → violet."),
  Q("chm102_t1_q3", T1, "Which alkali metal melts at only about 29 °C — just above room temperature?",
    ["Lithium", "Sodium", "Potassium", "Caesium"], 3,
    "Caesium melts at ~29 °C. Melting point decreases down the group because atoms get larger and metallic bonding weaker."),
  Q("chm102_t1_q4", T1, "Potassium and caesium are commonly used in photoelectric cells because:",
    ["They have the highest ionization energies", "Light alone can eject electrons from their surfaces", "They are the densest alkali metals", "They form coloured compounds in water"], 1,
    "Their very low ionization energies mean ordinary light can eject their outer electrons, which is the photoelectric effect used in these cells."),
  Q("chm102_t1_q5", T1, "Going down Group IA (Li → Cs), ionization energy:",
    ["Increases", "Decreases", "Stays the same", "First decreases then increases"], 1,
    "As atoms get larger down the group, the outer electron is farther from the nucleus and more easily removed — so ionization energy decreases."),
  Q("chm102_t1_q6", T1, "NaHCO₃ is commonly used to:",
    ["Bleach fabric", "Soften hard water", "Neutralize stomach acid (antacid)", "Extract titanium"], 2,
    "Sodium bicarbonate (baking soda) is a mild base used to neutralize excess stomach acid."),
  Q("chm102_t1_q7", T1, "Alkaline earth metals form M²⁺ ions because:",
    ["They gain 2 electrons to complete their shell", "They have 2 electrons in their outermost shell that they lose", "They share 2 electrons with another metal", "Their d-orbitals are partially filled"], 1,
    "Group IIA elements have ns² configuration and lose both electrons to form M²⁺ ions."),
  Q("chm102_t1_q8", T1, "Which alkaline earth metal does NOT give a characteristic flame colour?",
    ["Calcium", "Strontium", "Barium", "Beryllium"], 3,
    "Be and Mg hold their electrons too tightly to be excited by a flame. Ca → brick red, Sr → crimson, Ba → apple green."),
  Q("chm102_t1_q9", T1, "The diagonal relationship means Be behaves similarly to:",
    ["Magnesium", "Aluminium", "Sodium", "Boron"], 1,
    "Beryllium shows a diagonal relationship with Aluminium — both form covalent, amphoteric oxides and are rendered passive by concentrated HNO₃."),
  Q("chm102_t1_q10", T1, "Which calcium compound is used to make Plaster of Paris?",
    ["CaCO₃", "CaSO₄ (gypsum)", "Ca(OH)₂", "CaO"], 1,
    "Gypsum (CaSO₄·2H₂O) is the raw material for Plaster of Paris."),
  Q("chm102_t1_q11", T1, "CaO (quicklime) is used to make:",
    ["Cement only", "Bleaching powder and calcium carbide", "Plaster of Paris", "Sodium carbonate"], 1,
    "Quicklime is used to make bleaching powder and calcium carbide among other things."),
  Q("chm102_t1_q12", T1, "Radium salts are notable for use in:",
    ["Photoelectric cells", "Treating cancer and luminous paints", "Fireworks", "Laundry detergents"], 1,
    "Radium's radioactivity has been used to treat cancer and in historical luminous paints."),

  // --- T2: Group IVA & Carbon Allotropes ---
  Q("chm102_t2_q1", T2, "Which of these is a semimetal (metalloid) in Group IVA?",
    ["Carbon", "Germanium", "Tin", "Lead"], 1,
    "Carbon is a non-metal; Si and Ge are metalloids; Sn and Pb are metals."),
  Q("chm102_t2_q2", T2, "In diamond, each carbon atom is:",
    ["sp² hybridised with 3 bonds", "sp³ hybridised bonded tetrahedrally to 4 other C atoms", "sp hybridised in a linear arrangement", "Unhybridised"], 1,
    "Diamond has sp³ carbons bonded to 4 other carbons in a 3D tetrahedral network — the reason it is the hardest natural material."),
  Q("chm102_t2_q3", T2, "Graphite conducts electricity because:",
    ["It has a 3D tetrahedral network", "It has free π electrons between layers", "It contains metal impurities", "Its bonds are ionic"], 1,
    "In graphite each C is sp² and uses 3 electrons for σ bonds; the 4th is delocalised, allowing electrical conduction."),
  Q("chm102_t2_q4", T2, "Buckminsterfullerene (C₆₀) consists of:",
    ["12 hexagons only", "20 hexagons and 12 pentagons", "Only pentagons", "30 hexagons"], 1,
    "C₆₀ has 20 hexagonal rings and 12 pentagonal rings arranged like a soccer ball."),
  Q("chm102_t2_q5", T2, "Fullerenes were first discovered in:",
    ["1865", "1928", "1985", "1996"], 2,
    "Fullerenes were discovered in 1985 (Nobel Prize in Chemistry followed in 1996)."),
  Q("chm102_t2_q6", T2, "Coke is used in metallurgy primarily as:",
    ["An insulator", "A reducing agent to extract metals from ores", "A catalyst in the Haber process", "A semiconductor"], 1,
    "Coke (a form of carbon) is the principal reducing agent in the extraction of metals such as iron from their oxides."),
  Q("chm102_t2_q7", T2, "Tin is commonly used to:",
    ["Make transistors", "Coat mild steel to prevent rust", "Make solar cells", "Shield radioactive experiments"], 1,
    "Tin plating protects mild steel from corrosion (tin cans). Lead is used for radioactivity shielding."),

  // --- T3: Transition Metals & Coordination Compounds ---
  Q("chm102_t3_q1", T3, "A transition metal is best defined as an element:",
    ["In the s-block", "Whose atoms (or common ions) have a partially filled d subshell", "That only forms +1 ions", "Found in Group VIII only"], 1,
    "Transition metals have atoms — or common ions — with a partially filled d subshell."),
  Q("chm102_t3_q2", T3, "Why are Zn, Cd and Hg usually NOT classed as true transition metals?",
    ["Their atomic radii are too small", "They have completely filled d subshells", "They are radioactive", "They are in the f-block"], 1,
    "Zn, Cd, Hg all have full d¹⁰ subshells in both the atom and their common ions, so they are not true transition metals."),
  Q("chm102_t3_q3", T3, "The ground-state electronic configuration of Cr is anomalous and is:",
    ["[Ar] 4s² 3d⁴", "[Ar] 4s¹ 3d⁵", "[Ar] 4s² 3d⁵", "[Ar] 4s¹ 3d⁴"], 1,
    "Cr is 4s¹ 3d⁵ (not 4s² 3d⁴) — a half-filled d subshell is extra stable."),
  Q("chm102_t3_q4", T3, "The electronic configuration of the Fe²⁺ ion is:",
    ["[Ar] 4s² 3d⁴", "[Ar] 3d⁶", "[Ar] 4s¹ 3d⁵", "[Ar] 3d⁵"], 1,
    "Transition metals lose 4s electrons before 3d, so Fe²⁺ is [Ar] 3d⁶, not [Ar] 4s² 3d⁴."),
  Q("chm102_t3_q5", T3, "The highest oxidation state shown by manganese is:",
    ["+3", "+5", "+7", "+9"], 2,
    "Mn can reach +7 (e.g., in MnO₄⁻), the highest oxidation state among the 3d series."),
  Q("chm102_t3_q6", T3, "Transition metals act as excellent catalysts mainly because:",
    ["They are soft metals", "They can readily change oxidation states and donate/accept electrons", "They are noble metals", "They have filled d subshells"], 1,
    "Variable oxidation states allow transition metals to easily exchange electrons during reactions, making them effective catalysts."),
  Q("chm102_t3_q7", T3, "In a coordination compound, a ligand acts as a:",
    ["Lewis acid", "Lewis base (electron-pair donor)", "Reducing agent", "Counter ion"], 1,
    "Ligands donate lone pairs to the central metal (Lewis acid) forming coordinate (dative) bonds."),
  Q("chm102_t3_q8", T3, "Which of the following is a bidentate ligand?",
    ["NH₃", "Cl⁻", "Ethylenediamine (en)", "H₂O"], 2,
    "Ethylenediamine has two N-donor atoms; NH₃, Cl⁻ and H₂O are monodentate."),
  Q("chm102_t3_q9", T3, "EDTA is described as a chelating agent because it:",
    ["Has exactly one donor atom", "Grips the central metal with multiple donor atoms like a claw", "Is a noble gas", "Is a counter ion"], 1,
    "Chelating agents are bidentate/polydentate ligands that grip the metal tightly like a claw (EDTA has 6 donor atoms)."),
  Q("chm102_t3_q10", T3, "In [PtCl₆]²⁻, the oxidation state of platinum is:",
    ["+2", "+3", "+4", "+6"], 2,
    "Each Cl is −1; total ligand charge = −6; overall = −2; so Pt = +4."),
  Q("chm102_t3_q11", T3, "The IUPAC name of K₄[Fe(CN)₆] is:",
    ["Potassium hexacyanoiron(II)", "Potassium hexacyanoferrate(II)", "Potassium ferricyanide", "Hexacyano potassium ferrate(III)"], 1,
    "The anion gets the -ate suffix, so Fe becomes ferrate; 6 CN⁻ ligands named as hexacyano; Fe oxidation state +2 → (II)."),
  Q("chm102_t3_q12", T3, "A complex that contains only ONE type of ligand is described as:",
    ["Heteroleptic", "Homoleptic", "Chelate", "Inner-sphere"], 1,
    "Homoleptic = one ligand type (e.g. [Co(NH₃)₆]³⁺). Heteroleptic = more than one type."),

  // --- T4: Sodium, Aluminium & Non-metals ---
  Q("chm102_t4_q1", T4, "Sodium is industrially extracted by:",
    ["Thermal decomposition of Na₂CO₃", "Electrolysis of concentrated NaCl (brine)", "Reduction of Na₂O with carbon", "Fractional distillation of liquid air"], 1,
    "Sodium is obtained by electrolysis of brine — Na at the cathode, Cl₂ at the anode."),
  Q("chm102_t4_q2", T4, "Sodium is stored under paraffin oil because:",
    ["It evaporates easily", "It reacts quickly with air and water vapour", "It dissolves in water only slowly", "It is radioactive"], 1,
    "Na tarnishes rapidly in air, forming Na₂O → NaOH → Na₂CO₃. Paraffin oil protects it from moisture and oxygen."),
  Q("chm102_t4_q3", T4, "The flame colour of sodium is:",
    ["Brick red", "Golden yellow", "Apple green", "Violet"], 1,
    "Sodium gives a persistent golden-yellow flame — often used as a diagnostic test."),
  Q("chm102_t4_q4", T4, "The main ore of aluminium is:",
    ["Cryolite", "Bauxite", "Kaolin", "Corundum"], 1,
    "Bauxite (up to 60% Al₂O₃) is the principal aluminium ore. The others are minor sources."),
  Q("chm102_t4_q5", T4, "In the extraction of Al, cryolite (Na₃AlF₆) is added mainly to:",
    ["React with alumina", "Lower the melting point of the electrolyte to about 1000 °C", "Supply the aluminium", "Act as a catalyst"], 1,
    "Pure alumina melts at ~2000 °C. Dissolving it in molten cryolite drops the melting point to ~1000 °C, making electrolysis feasible."),
  Q("chm102_t4_q6", T4, "Aluminium is amphoteric — it reacts with:",
    ["Only acids", "Only bases", "Both acids and alkalis releasing H₂", "Neither acids nor bases"], 2,
    "Al reacts with dilute acids and with NaOH/KOH to release hydrogen — the key amphoteric behaviour shared with Be."),
  Q("chm102_t4_q7", T4, "In the thermite reaction (2Al + Fe₂O₃ → Al₂O₃ + 2Fe), aluminium acts as a:",
    ["Catalyst", "Reducing agent", "Oxidising agent", "Neutral ligand"], 1,
    "Al reduces iron(III) oxide to molten iron; Al itself is oxidised to Al₂O₃. The reaction is highly exothermic — used in welding."),
  Q("chm102_t4_q8", T4, "Adding NaOH to an aluminium salt solution gives:",
    ["A blue precipitate soluble in excess", "A white gelatinous precipitate that dissolves in excess NaOH", "No reaction", "A red-brown precipitate"], 1,
    "Al³⁺ + 3OH⁻ → Al(OH)₃ (white jelly). With excess OH⁻, Al(OH)₃ dissolves as [Al(OH)₄]⁻."),
  Q("chm102_t4_q9", T4, "Nitrogen exists as N₂ with a:",
    ["Single bond", "Double bond", "Triple bond", "Coordinate bond only"], 2,
    "N₂ has a strong triple bond (N≡N), responsible for its inertness under normal conditions."),
  Q("chm102_t4_q10", T4, "The industrial source of pure nitrogen gas is:",
    ["Reaction of NH₃ with Cl₂", "Fractional distillation of liquid air", "Electrolysis of brine", "Heating sodium azide"], 1,
    "Industrial N₂ is produced by fractional distillation of liquid air. N₂ boils at −196 °C; O₂ at −183 °C."),
  Q("chm102_t4_q11", T4, "In the Haber process: N₂ + 3H₂ → 2NH₃. What is typically used as a catalyst?",
    ["Vanadium", "Iron", "Platinum", "Nickel"], 1,
    "Iron is the classical catalyst for the Haber process."),
  Q("chm102_t4_q12", T4, "Chlorine is prepared in the laboratory by:",
    ["Electrolysis of molten NaCl", "Fractional distillation of liquid air", "Oxidation of concentrated HCl with MnO₂ or KMnO₄", "Heating NaClO₃"], 2,
    "Lab prep oxidises concentrated HCl with MnO₂ or KMnO₄. Industrial chlorine comes from electrolysis of brine."),
  Q("chm102_t4_q13", T4, "Chlorine can bleach dyes because it:",
    ["Is a reducing agent in water", "Is a powerful oxidising agent in the presence of water", "Dissolves pigments physically", "Emits UV light"], 1,
    "In the presence of water, Cl₂ acts as a strong oxidiser that destroys coloured (non-carbon) dyes."),
  Q("chm102_t4_q14", T4, "In the reaction 2FeCl₂ + Cl₂ → 2FeCl₃, chlorine is acting as a(n):",
    ["Reducing agent", "Oxidising agent", "Catalyst", "Ligand"], 1,
    "Cl₂ oxidises Fe²⁺ to Fe³⁺, so chlorine is an oxidising agent."),

  // --- T5: Benzene & Aromatic Chemistry ---
  Q("chm102_t5_q1", T5, "When 1 mole of benzene is fully hydrogenated with a Ni catalyst, how many moles of H₂ are absorbed?",
    ["1", "2", "3", "6"], 2,
    "Benzene adds 3 moles of H₂ to give cyclohexane (C₆H₁₂), confirming 3 double-bond equivalents."),
  Q("chm102_t5_q2", T5, "All C–C bond lengths in benzene are equal because:",
    ["Benzene has alternating single and double bonds", "The π electrons are delocalised over the ring", "The ring is non-planar", "There is no π bonding in benzene"], 1,
    "The 6 π electrons are delocalised around the ring, so every C–C bond has the same intermediate length (1.39 Å)."),
  Q("chm102_t5_q3", T5, "According to Hückel's rule, an aromatic compound must have (4n+2) π electrons. For benzene, n =",
    ["0", "1", "2", "3"], 1,
    "Benzene has 6 π electrons; 4(1)+2 = 6, so n = 1."),
  Q("chm102_t5_q4", T5, "Which is NOT a condition for aromaticity?",
    ["The molecule is cyclic", "The molecule is flat (planar)", "It must contain at least one heteroatom", "It has a continuous conjugated π system with (4n+2) π electrons"], 2,
    "Aromatic compounds must be cyclic, planar and follow Hückel's rule. They do not need a heteroatom."),
  Q("chm102_t5_q5", T5, "Benzene prefers substitution over addition reactions because:",
    ["Addition would break the sigma framework", "Substitution preserves the aromatic π system and its resonance stability", "Addition is always slower", "Benzene has no π electrons"], 1,
    "Addition would destroy aromaticity and cost the 150 kJ/mol resonance stability, so substitution is preferred."),
  Q("chm102_t5_q6", T5, "The Lewis-acid catalyst used for halogenation of benzene with Cl₂ is:",
    ["AlCl₃", "FeCl₃", "H₂SO₄", "HNO₃"], 1,
    "For halogenation: FeCl₃ / FeBr₃ are used. AlCl₃ is used for Friedel-Crafts alkylation/acylation."),
  Q("chm102_t5_q7", T5, "In nitration of benzene (HNO₃/H₂SO₄), the active electrophile is:",
    ["NO⁻", "NO₂⁻", "NO₂⁺ (nitronium ion)", "HNO₃ directly"], 2,
    "H₂SO₄ protonates and dehydrates HNO₃ to give the nitronium ion NO₂⁺, which attacks the benzene ring."),
  Q("chm102_t5_q8", T5, "Friedel-Crafts acylation of benzene produces:",
    ["An alkylbenzene", "An aryl ketone", "A nitro compound", "A sulphonic acid"], 1,
    "Benzene + RCOCl with AlCl₃ gives an aryl ketone (Ar–CO–R) plus HCl."),

  // --- T6: Alcohols, Phenols, Aldehydes & Ketones ---
  Q("chm102_t6_q1", T6, "Reducing a ketone with NaBH₄ gives:",
    ["A primary alcohol", "A secondary alcohol", "A tertiary alcohol", "An aldehyde"], 1,
    "Ketones reduce to secondary alcohols. Aldehydes reduce to primary alcohols."),
  Q("chm102_t6_q2", T6, "The DOW process for industrial phenol production uses:",
    ["Benzene + H₂SO₄ fused with NaOH", "Chlorobenzene + dilute NaOH at 300 °C and 3000 psi", "Cumene + O₂", "Oxidation of phenol ethers"], 1,
    "DOW process: chlorobenzene is heated with dilute NaOH at ~300 °C and 3000 psi to give phenol."),
  Q("chm102_t6_q3", T6, "Phenols are highly reactive in electrophilic aromatic substitution because:",
    ["The OH group is strongly electron-withdrawing", "The oxygen lone pairs donate electron density into the ring, making it electron-rich", "Phenol is non-aromatic", "The OH becomes an electrophile"], 1,
    "The lone pairs on oxygen push electron density into the ring, activating it strongly for EAS."),
  Q("chm102_t6_q4", T6, "In the IUPAC system, an aldehyde is named by changing the parent alkane's final -e to:",
    ["-ol", "-al", "-one", "-oic acid"], 1,
    "Aldehyde → -al (e.g., ethanal). Ketone → -one. Alcohol → -ol. Carboxylic acid → -oic acid."),
  Q("chm102_t6_q5", T6, "Which of these is the common name for methanal?",
    ["Acetaldehyde", "Propionaldehyde", "Formaldehyde", "Butyraldehyde"], 2,
    "Methanal (HCHO) is commonly called formaldehyde; ethanal is acetaldehyde."),
  Q("chm102_t6_q6", T6, "Aldehydes are more reactive than ketones toward nucleophiles because:",
    ["Aldehydes have no α-hydrogens", "Ketones have an extra C=O", "Ketones have more electron-donating alkyl groups and more steric hindrance", "Aldehydes are always aromatic"], 2,
    "Alkyl groups on ketones donate electrons (reducing electrophilicity of C=O) and add steric hindrance, making ketones less reactive."),
  Q("chm102_t6_q7", T6, "In Fehling's test for aldehydes, a positive result is:",
    ["A silver mirror", "A brick-red precipitate of Cu₂O", "A blue solution", "A white precipitate"], 1,
    "Fehling's test gives a brick-red Cu₂O precipitate with aldehydes; ketones give no change."),
  Q("chm102_t6_q8", T6, "Tollens' test gives which observation with an aldehyde?",
    ["White precipitate", "Red-brown precipitate", "A shiny silver mirror on the tube wall", "No change"], 2,
    "Aldehydes reduce Ag⁺ to metallic Ag, which deposits as a silver mirror on the glass. Ketones give no change."),
  Q("chm102_t6_q9", T6, "Oxidation of a primary alcohol by PCC typically gives:",
    ["A carboxylic acid", "An aldehyde (stops there)", "A ketone", "An ester"], 1,
    "PCC is a mild oxidant that stops at the aldehyde. Stronger oxidants (e.g. KMnO₄) go on to the carboxylic acid."),

  // --- T7: Carboxylic Acids, Derivatives & Amines ---
  Q("chm102_t7_q1", T7, "The IUPAC name for CH₃COOH is:",
    ["Methanoic acid", "Propanoic acid", "Ethanoic acid", "Butanoic acid"], 2,
    "Two carbons + -oic acid → ethanoic acid (common name: acetic acid)."),
  Q("chm102_t7_q2", T7, "The natural source of formic acid (methanoic acid) is:",
    ["Vinegar", "Ants", "Milk", "Butter"], 1,
    "HCOOH is the acid produced by ants (Latin formica = ant); CH₃COOH is vinegar; propanoic acid is in milk; butyric in butter."),
  Q("chm102_t7_q3", T7, "Reducing a carboxylic acid to a primary alcohol requires:",
    ["NaBH₄", "LiAlH₄", "PCC", "H₂/Ni"], 1,
    "NaBH₄ is too weak to reduce RCOOH; only LiAlH₄ (a strong hydride) can reduce it all the way to a primary alcohol."),
  Q("chm102_t7_q4", T7, "In the order of reactivity of carboxylic acid derivatives toward nucleophilic acyl substitution, the correct order (most → least reactive) is:",
    ["Amide > Ester > Anhydride > Acyl halide", "Acyl halide > Anhydride > Ester > Amide", "Ester > Amide > Acyl halide > Anhydride", "Anhydride > Amide > Ester > Acyl halide"], 1,
    "The better the leaving group the more reactive the derivative: Acyl halides > anhydrides > esters > amides."),
  Q("chm102_t7_q5", T7, "Base hydrolysis of an ester is specifically called:",
    ["Esterification", "Saponification", "Aminolysis", "Alcoholysis"], 1,
    "Hydrolysis of an ester in basic solution is called saponification — the reaction used in soap making."),
  Q("chm102_t7_q6", T7, "Fischer esterification is:",
    ["Carboxylic acid + alcohol + HCl (catalyst) → ester + H₂O", "Acyl chloride + alcohol → ester + HCl", "Ester + NaOH → carboxylate + alcohol", "Amide + alcohol → ester + amine"], 0,
    "Classical Fischer esterification couples a carboxylic acid and an alcohol with HCl or H₂SO₄ catalysis to give the ester and water."),
  Q("chm102_t7_q7", T7, "Reduction of an amide with LiAlH₄ gives:",
    ["A carboxylic acid", "An alcohol", "An amine", "An aldehyde"], 2,
    "LiAlH₄ reduces the C=O of an amide to CH₂, converting R-CONH₂ to R-CH₂-NH₂ (an amine)."),
  Q("chm102_t7_q8", T7, "A tertiary amine is one in which the nitrogen is bonded to:",
    ["One alkyl/aryl group and two hydrogens", "Two alkyl/aryl groups and one hydrogen", "Three alkyl/aryl groups and no hydrogen", "Four alkyl/aryl groups (positively charged)"], 2,
    "1° = 1 R + 2 H; 2° = 2 R + 1 H; 3° = 3 R + 0 H; 4° ammonium = 4 R, positively charged."),
  Q("chm102_t7_q9", T7, "Aromatic amines (e.g., aniline) are LESS basic than alkyl amines because:",
    ["The ring is electron-donating", "The nitrogen lone pair is delocalised into the benzene ring", "They have no lone pair", "They are cyclic"], 1,
    "Delocalisation of the lone pair into the ring reduces its availability for protonation, lowering basicity."),
  Q("chm102_t7_q10", T7, "The standard way to make an arylamine is to reduce a nitro compound using:",
    ["LiAlH₄", "SnCl₂/H₃O⁺, then NaOH", "NaBH₄", "H₂/Pt at room temperature only"], 1,
    "Nitrobenzene → aniline is typically done with Sn/HCl or SnCl₂/H₃O⁺ followed by base."),
  Q("chm102_t7_q11", T7, "In Hofmann elimination, an amine is first converted to a quaternary ammonium salt by reacting with:",
    ["CH₃OH", "Excess CH₃I", "HCl", "H₂O/heat"], 1,
    "Excess methyl iodide exhaustively methylates the amine to a 4° ammonium salt, which is then treated with Ag₂O/H₂O/heat to give the alkene."),

  // --- T8: Qualitative Analysis ---
  Q("chm102_t8_q1", T8, "Which salt gives a persistent golden-yellow flame but does NOT decompose on heating?",
    ["CaCl₂", "Na₂CO₃", "Pb(NO₃)₂", "ZnO"], 1,
    "Sodium gives a yellow flame and Group I carbonates are thermally very stable."),
  Q("chm102_t8_q2", T8, "Heating Pb(NO₃)₂ produces brown fumes. These fumes are:",
    ["Br₂", "Cl₂", "NO₂", "SO₂"], 2,
    "Heavy-metal nitrates decompose to the oxide, NO₂ (brown, toxic) and O₂. 2Pb(NO₃)₂ → 2PbO + 4NO₂ + O₂."),
  Q("chm102_t8_q3", T8, "When Pb(NO₃)₂ is heated, the residue is:",
    ["White both hot and cold", "Yellow when hot and white when cold", "Black both hot and cold", "Red when hot and yellow when cold"], 1,
    "PbO is the residue — yellow when hot, white when cold (a classic diagnostic for lead nitrate)."),
  Q("chm102_t8_q4", T8, "Which salt shows absolutely no change on strong heating or in a flame test?",
    ["Na₂CO₃", "ZnO", "CaCl₂", "Pb(NO₃)₂"], 1,
    "ZnO is thermally very stable and zinc gives no characteristic flame colour."),
  Q("chm102_t8_q5", T8, "A brick-red (orange-red) flame colour is diagnostic for:",
    ["Na⁺", "Ca²⁺", "Cu²⁺", "Ba²⁺"], 1,
    "Ca²⁺ gives a characteristic brick-red/orange-red flame."),
  Q("chm102_t8_q6", T8, "Adding NaOH to a solution of an aluminium salt gives:",
    ["A blue precipitate insoluble in excess", "A white gelatinous precipitate that dissolves in excess NaOH", "A green precipitate", "No precipitate at all"], 1,
    "Al³⁺ + 3OH⁻ → Al(OH)₃ (white jelly). Excess OH⁻ dissolves the ppt as [Al(OH)₄]⁻."),
  Q("chm102_t8_q7", T8, "Mg²⁺ differs from Al³⁺ in the NaOH test in that its hydroxide precipitate:",
    ["Dissolves in excess NaOH", "Does NOT dissolve in excess NaOH", "Is blue", "Is green"], 1,
    "Mg(OH)₂ is white but insoluble in excess NaOH — this is how you distinguish Mg²⁺ from amphoteric Al³⁺."),
  Q("chm102_t8_q8", T8, "A copper(II) salt solution gives a blue precipitate with NaOH. With excess ammonia solution, you observe:",
    ["A red-brown precipitate", "A deep blue solution of [Cu(NH₃)₄]²⁺", "No change from the blue precipitate", "A green precipitate"], 1,
    "Excess NH₃ dissolves Cu(OH)₂ to give the deep blue tetraamminecopper(II) complex — unique to copper."),
  Q("chm102_t8_q9", T8, "The confirmatory test for Fe³⁺ with KSCN gives a:",
    ["Prussian blue precipitate", "Blood-red colour of [Fe(SCN)]²⁺", "Turnbull's blue precipitate", "Yellow colour"], 1,
    "KSCN is the classic confirmatory test — Fe³⁺ + SCN⁻ → intense blood-red [Fe(SCN)]²⁺."),
  Q("chm102_t8_q10", T8, "A green precipitate with NaOH that slowly turns brown on standing indicates:",
    ["Cu²⁺", "Fe²⁺", "Fe³⁺", "Al³⁺"], 1,
    "Fe(OH)₂ is green but oxidises in air to red-brown Fe(OH)₃ — a classic Fe²⁺ behaviour."),
  Q("chm102_t8_q11", T8, "The Prussian blue test uses:",
    ["K₃[Fe(CN)₆] with Fe²⁺", "K₄[Fe(CN)₆] with Fe³⁺", "KSCN with Fe²⁺", "NH₄OH with Cu²⁺"], 1,
    "Prussian blue forms when K₄[Fe(CN)₆] (potassium ferrocyanide) is added to Fe³⁺; Turnbull's blue forms with K₃[Fe(CN)₆] and Fe²⁺."),

  // --- T9: History, Bonding & Nanotechnology ---
  Q("chm102_t9_q1", T9, "The vital force theory of organic compounds was overturned by:",
    ["Lavoisier in 1784", "Berzelius in 1807", "Wöhler's 1828 synthesis of urea", "Kekulé's benzene structure"], 2,
    "Wöhler's 1828 synthesis of urea from ammonium cyanate — a 'living' compound made in the lab — discredited vitalism."),
  Q("chm102_t9_q2", T9, "Kekulé's key 1865 contribution was:",
    ["Discovering penicillin", "Proposing the ring structure of benzene", "Formulating Hückel's rule", "Inventing the Haber process"], 1,
    "In 1865 Kekulé proposed benzene as a six-membered ring with alternating double bonds (later refined as a resonance hybrid)."),
  Q("chm102_t9_q3", T9, "A carbon atom involved in one C=C double bond is:",
    ["sp hybridised", "sp² hybridised (planar, 120°)", "sp³ hybridised (tetrahedral, 109.5°)", "unhybridised"], 1,
    "sp² carbon = 1 double bond; sp³ = all single bonds (109.5°); sp = triple bond (linear, 180°)."),
  Q("chm102_t9_q4", T9, "A triple bond between two carbons consists of:",
    ["3 sigma bonds", "3 pi bonds", "1 sigma and 2 pi bonds", "2 sigma and 1 pi bond"], 2,
    "A triple bond = 1 sigma + 2 pi bonds. Single = 1σ; Double = 1σ + 1π."),
  Q("chm102_t9_q5", T9, "The bond angles in ethyne (HC≡CH) are:",
    ["90°", "109.5°", "120°", "180°"], 3,
    "sp-hybridised carbons in C≡C give a linear geometry (180°)."),
  Q("chm102_t9_q6", T9, "Which element is the most electronegative?",
    ["Oxygen", "Chlorine", "Nitrogen", "Fluorine"], 3,
    "Fluorine is the most electronegative element on the periodic table."),
  Q("chm102_t9_q7", T9, "The idea of nanotechnology was first proposed in 1959 by:",
    ["Richard Smalley", "Richard Feynman (lecture: 'There's Plenty of Room at the Bottom')", "Andre Geim", "Sumio Iijima"], 1,
    "Feynman's 1959 lecture 'There's Plenty of Room at the Bottom' foreshadowed nanotechnology."),
  Q("chm102_t9_q8", T9, "One nanometre (1 nm) is equal to:",
    ["10⁻³ m", "10⁻⁶ m", "10⁻⁹ m", "10⁻¹² m"], 2,
    "Nano = one-billionth, so 1 nm = 10⁻⁹ m."),
  Q("chm102_t9_q9", T9, "Carbon nanotubes were first observed and characterised in 1991 by:",
    ["Harold Kroto", "Sumio Iijima", "Richard Feynman", "Andre Geim"], 1,
    "Sumio Iijima (NEC, Japan) observed CNTs by high-resolution electron microscopy in 1991."),
  Q("chm102_t9_q10", T9, "Graphene is best described as:",
    ["A 3D cubic lattice of carbon atoms", "A single flat layer of sp² carbon atoms in a hexagonal lattice", "A spherical cluster of 60 carbon atoms", "A cylindrical tube of sp³ carbon"], 1,
    "Graphene = single hexagonal layer of sp² carbons — the most basic 2D form of nano-carbon."),
  Q("chm102_t9_q11", T9, "Two general approaches in nanotechnology are bottom-up and top-down. The top-down approach involves:",
    ["Assembling structures atom by atom from below", "Starting from a bulk material and cutting/etching it down", "Using only biological processes", "Stacking graphene layers"], 1,
    "Top-down: start with bulk and reduce it (e.g., microlithography). Bottom-up: assemble atoms/molecules into structures (self-assembly)."),

  // --- Extras ---
  Q("chm102_t1_q13", T1, "Which alkali metal is stored under paraffin oil?",
    ["All of them react slowly enough to sit in air", "Sodium (because it reacts rapidly with air and moisture)", "Lithium is the only one", "None — all are kept in water"], 1,
    "Group IA metals react vigorously with air/water. Sodium (and K) must be stored under paraffin oil to exclude moisture and oxygen."),
  Q("chm102_t1_q14", T1, "Going down Group IIA, atomic radius:",
    ["Decreases", "Increases", "Stays the same", "First increases then decreases"], 1,
    "Down any main group, atomic radius increases as new electron shells are added."),
  Q("chm102_t2_q8", T2, "Which of the following is NOT an allotrope of carbon?",
    ["Diamond", "Graphite", "Fullerene", "Silicon carbide"], 3,
    "Silicon carbide is a compound, not an allotrope of carbon. Allotropes of C include diamond, graphite, fullerenes, graphene and carbon nanotubes."),
  Q("chm102_t3_q13", T3, "Which geometry is typical for a 6-coordinate complex like [Fe(H₂O)₆]²⁺?",
    ["Tetrahedral", "Square planar", "Octahedral", "Trigonal bipyramidal"], 2,
    "Six equivalent ligands arrange themselves in octahedral geometry around the central metal."),
  Q("chm102_t5_q9", T5, "Friedel-Crafts alkylation uses benzene with RX and which catalyst?",
    ["FeCl₃", "AlCl₃", "H₂SO₄", "Zn dust"], 1,
    "Anhydrous AlCl₃ generates the carbocation electrophile for Friedel-Crafts alkylation and acylation."),
  Q("chm102_t6_q10", T6, "Which reagent is a GOOD test to distinguish an aldehyde from a ketone?",
    ["Br₂/CCl₄", "Tollens' reagent (ammoniacal AgNO₃)", "Conc. H₂SO₄", "Na metal"], 1,
    "Tollens' oxidises aldehydes to carboxylates giving a silver mirror; ketones do not react."),
  Q("chm102_t7_q12", T7, "An amide reacts with water under acidic or basic conditions to give:",
    ["An alcohol and an ester", "A carboxylic acid (or carboxylate) and an amine", "An aldehyde and water", "Two amines"], 1,
    "Hydrolysis of an amide regenerates the carboxylic acid (acid) or carboxylate (base) plus the free amine."),
  Q("chm102_t8_q12", T8, "Iron(III) hydroxide is observed as:",
    ["A green precipitate", "A red-brown precipitate insoluble in excess NaOH", "A blue precipitate soluble in excess NH₃", "A white gelatinous precipitate"], 1,
    "Fe(OH)₃ is red-brown and does NOT dissolve in excess NaOH, distinguishing it from amphoteric Al(OH)₃."),
  Q("chm102_t9_q12", T9, "Which is a key property that makes carbon nanotubes exceptional?",
    ["Very low tensile strength", "Exceptional mechanical strength and electrical conductivity", "They melt below 100 °C", "They are chemically inert to all reagents"], 1,
    "CNTs are among the strongest materials known and conduct electricity extremely well — the reason for their use in advanced composites and electronics."),
];

export const CHM_102_SEED: Course = {
  id: "chm102",
  name: "CHM 102 — General Chemistry II",
  description: "practice question for this semester",
  createdAt: Date.now(),
  updatedAt: Date.now(),
  questions,
};
