import type { Course, Question } from "../types";

const Q = (
  id: string,
  topic: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question => ({ id, type: "mcq", topic, question, options, correctIndex, explanation });

const T1 = "Ethnic Groups & Culture";
const T2 = "Amalgamation of 1914";
const T3 = "Social Justice & Law";
const T4 = "Trade & Self-Reliance";
const T5 = "Hausa, Nupe, Kanuri & Fulani";

const questions: Question[] = [
  // --- Topic 1: Ethnic Groups & Culture ---
  Q("gst112_t1_q1", T1, "Culture is best defined as:",
    ["A country's dances and festivals", "The total way of life of a people", "The religion of a group", "The art and music of a nation only"], 1,
    "Culture is the total way of life of a people — language, food, dress, beliefs, art, music, laws and behaviour."),
  Q("gst112_t1_q2", T1, "Which of these is an example of NON-material culture?",
    ["Tools", "Buildings", "Values and traditions", "Sculpture"], 2,
    "Non-material culture refers to abstract things like religion, language, values and traditions. Tools, buildings and sculpture are material culture."),
  Q("gst112_t1_q3", T1, "Approximately how many ethnic groups does Nigeria have?",
    ["Over 50", "Over 100", "Over 250", "Over 500"], 2,
    "Nigeria has over 250 ethnic groups, making it one of the most ethnically diverse countries in the world."),
  Q("gst112_t1_q4", T1, "The three largest ethnic groups in Nigeria are:",
    ["Hausa, Yoruba, Fulani", "Hausa, Yoruba, Igbo", "Igbo, Ibibio, Yoruba", "Fulani, Hausa, Kanuri"], 1,
    "The three largest ethnic groups are the Hausa, Yoruba and Igbo."),
  Q("gst112_t1_q5", T1, "Traditional Igbo society is best described as:",
    ["Monarchical", "Feudal", "Egalitarian", "Theocratic"], 2,
    "Igbo society is egalitarian — no kings, everyone is considered equal."),
  Q("gst112_t1_q6", T1, "Which deity is associated with thunder in Igbo traditional religion?",
    ["Ala", "Amadioha", "Ahiajoku", "Sango"], 1,
    "Amadioha is the Igbo god of thunder. Ala is the earth goddess and Ahiajoku the agriculture deity. Sango is Yoruba."),
  Q("gst112_t1_q7", T1, "The Yoruba Supreme Being is:",
    ["Amadioha", "Sango", "Olodumare", "Ala"], 2,
    "Olodumare is the Yoruba Supreme Being. Sango is the god of thunder, not the Supreme Being."),
  Q("gst112_t1_q8", T1, "The Yoruba extended family compound is called:",
    ["Agbo-Ile", "Sarki", "Obi", "Omoluabi"], 0,
    "Agbo-Ile refers to the extended Yoruba family compound; Omoluabi is a person of good character."),
  Q("gst112_t1_q9", T1, "The ideal Yoruba person of good character is called:",
    ["Omoluabi", "Agbo-Ile", "Sarki", "Omo-Oba"], 0,
    "Omoluabi describes someone of good character in Yoruba culture."),
  Q("gst112_t1_q10", T1, "Islam came to Hausa land in the:",
    ["12th century", "14th century", "16th century", "19th century"], 1,
    "Islam reached Hausa land in the 14th century, introduced by Fulani missionaries."),
  Q("gst112_t1_q11", T1, "The Hausa language is the second most widely spoken indigenous language in Africa after:",
    ["Yoruba", "Arabic", "Swahili", "Amharic"], 2,
    "Swahili is the most widely spoken indigenous language in Africa; Hausa comes second."),
  Q("gst112_t1_q12", T1, "The Fulani originally came from:",
    ["Morocco", "Egypt", "Upper Senegal", "Sudan"], 2,
    "The Fulani trace their origin to Upper Senegal, descended from Tuculor women and Berber traders."),
  Q("gst112_t1_q13", T1, "Fulani Bororo are best described as:",
    ["Town-dwelling traders", "Nomadic cattle rearers", "Islamic scholars only", "Craftsmen and weavers"], 1,
    "Fulani Bororo are the nomadic cattle rearers. Fulani Gida are the town-dwelling traders and craftsmen."),
  Q("gst112_t1_q14", T1, "The Kanem-Borno Empire lasted approximately:",
    ["About 300 years", "About 700 years", "Over 1,000 years", "Over 1,500 years"], 2,
    "The Kanem-Borno Empire (AD 774–1810) lasted over 1,000 years — one of the longest dynasties in world history."),
  Q("gst112_t1_q15", T1, "The Kanuri are predominantly:",
    ["Sunni Muslims", "Shi'a Muslims", "Catholic Christians", "Traditional religionists"], 0,
    "The Kanuri are predominantly Sunni Muslims."),
  Q("gst112_t1_q16", T1, "The founder of the Nupe Kingdom was:",
    ["Usman Dan Fodio", "Tsoede (Edegi)", "Idris Alooma", "Ayegba Om'Idoko"], 1,
    "Tsoede (also known as Edegi), born 1465 to an Igala father and Nupe mother, founded the Nupe Kingdom. Bida is its traditional headquarters."),
  Q("gst112_t1_q17", T1, "Which group introduced the Egungun masquerade to the Yoruba?",
    ["Hausa", "Igala", "Nupe", "Kanuri"], 2,
    "The Nupe contributed the Egungun masquerade to Yoruba cultural practice."),
  Q("gst112_t1_q18", T1, "The Tiv people are believed to have migrated from the:",
    ["Niger Delta", "Cameroon-Obudu Plateau", "Sokoto Caliphate", "Jos Plateau"], 1,
    "The Tiv migrated from the Cameroon-Obudu Plateau in four waves between 1475 and 1900."),
  Q("gst112_t1_q19", T1, "The Mandyang (rain festival) is associated with which people?",
    ["Igala", "Birom", "Ebira", "Idoma"], 1,
    "The Birom on the Jos Plateau are known for Mandyang (rain festival) and Nshor (hunting festival)."),
  Q("gst112_t1_q20", T1, "The first Attah of Igala was:",
    ["Ayegba Om'Idoko", "Tsoede", "Bayajida", "Idris Alooma"], 0,
    "Ayegba Om'Idoko was the first king (Attah) of Igala, with headquarters in Idah."),
  Q("gst112_t1_q21", T1, "Islam spread to Northern Nigerian groups mainly through:",
    ["The Atlantic coast", "The Trans-Saharan trade", "The Nile River", "Portuguese missionaries"], 1,
    "Northern Nigeria's contact with North Africa and the Middle East was mainly via the Trans-Saharan trade, the route by which Islam spread."),
  Q("gst112_t1_q22", T1, "Which is an example of how Nigerian culture is preserved and promoted globally?",
    ["Abandoning indigenous languages", "Westernization of dress", "Nollywood and Afrobeats", "Replacing local cuisine with foreign food"], 2,
    "Nollywood films, Afrobeats music and the use of indigenous languages in media help preserve and export Nigerian culture."),

  // --- Topic 2: Amalgamation of 1914 ---
  Q("gst112_t2_q1", T2, "Nigeria was officially amalgamated on:",
    ["October 1, 1960", "January 1, 1914", "January 1, 1900", "June 12, 1914"], 1,
    "On January 1, 1914, Britain merged the Northern and Southern Protectorates into the Colony and Protectorate of Nigeria."),
  Q("gst112_t2_q2", T2, "The Governor-General at the 1914 amalgamation was:",
    ["Hugh Clifford", "Frederick Lugard", "Arthur Richards", "John Macpherson"], 1,
    "Frederick Lugard served as Governor-General of the newly amalgamated Nigeria."),
  Q("gst112_t2_q3", T2, "The Berlin Conference which divided Africa among European powers was held in:",
    ["1870–1871", "1884–1885", "1900–1901", "1914–1915"], 1,
    "The Berlin Conference of 1884–1885 partitioned Africa among European colonial powers."),
  Q("gst112_t2_q4", T2, "A MAIN economic reason for amalgamation was that:",
    ["The South was running a deficit funded by the North", "The North was running a deficit; the South's surplus funded it", "Both regions had equal surpluses", "Britain needed slave-trade revenue"], 1,
    "The Northern Protectorate ran at a loss; Britain used the South's surplus revenue to cover the shortfall, making unification financially attractive."),
  Q("gst112_t2_q5", T2, "Lugard's system of ruling through traditional leaders was called:",
    ["Direct Rule", "Assimilation", "Indirect Rule", "Theocracy"], 2,
    "Indirect Rule worked through existing traditional authorities — especially effective with the Northern emirate system."),
  Q("gst112_t2_q6", T2, "The 1929 Aba Women's War was primarily a reaction to:",
    ["The Sokoto Caliphate", "Warrant Chiefs imposed by the British", "The Fulani Jihad", "Missionary schools"], 1,
    "In the South, Britain imposed 'Warrant Chiefs' — artificial authorities — which sparked the 1929 Aba Women's War."),
  Q("gst112_t2_q7", T2, "Education spread faster in Southern Nigeria largely because of:",
    ["Oil wealth", "Missionary activities", "Trans-Saharan trade", "The Emirate system"], 1,
    "Christian missionaries were more active in the South; the North restricted missionary work to protect Islamic structures."),
  Q("gst112_t2_q8", T2, "Which of these is NOT a post-amalgamation Nigerian constitution?",
    ["Clifford (1922)", "Richards (1946)", "Lugard (1860)", "Lyttleton (1954)"], 2,
    "The Clifford, Richards, Macpherson and Lyttleton constitutions followed amalgamation. There was no 'Lugard 1860' constitution."),
  Q("gst112_t2_q9", T2, "Which political party was primarily associated with the Western Region?",
    ["NPC", "Action Group", "NCNC", "NEPU"], 1,
    "Parties formed along regional lines — NPC (North), Action Group (West), NCNC (East)."),
  Q("gst112_t2_q10", T2, "Britain extended control over the Nigerian area largely through:",
    ["The Royal Niger Company", "The East India Company", "Direct military conquest only", "A UN mandate"], 0,
    "The Royal Niger Company was the commercial vehicle through which Britain extended administrative control over the Niger region."),

  // --- Topic 3: Social Justice & Law ---
  Q("gst112_t3_q1", T3, "Social justice is best described as:",
    ["Punishment for criminals", "Fair and equal treatment of everyone in society", "The court system only", "A branch of civil law"], 1,
    "Social justice means fair and equal treatment — equal access to opportunities, resources and rights regardless of background."),
  Q("gst112_t3_q2", T3, "Which is NOT one of the four pillars of social justice?",
    ["Equity", "Diversity and Inclusion", "Economic growth", "Rule of Law"], 2,
    "The four pillars are Equity, Diversity & Inclusion, Human Rights Protection, and Rule of Law. Economic growth is an outcome, not a pillar."),
  Q("gst112_t3_q3", T3, "Economists commonly measure national development using:",
    ["Birth rate alone", "GDP and social indicators like access to water, electricity and schools", "The size of the army", "The number of political parties"], 1,
    "National development is measured using GDP alongside social indicators such as access to water, electricity, roads, housing and education."),
  Q("gst112_t3_q4", T3, "Criminal law deals with:",
    ["Disputes between individuals over contracts", "Crimes against society", "Agreements between countries", "Religious rules"], 1,
    "Criminal law addresses crimes against society — punishable by imprisonment, fines or death."),
  Q("gst112_t3_q5", T3, "The Bakassi Peninsula dispute between Nigeria and Cameroon is an example of:",
    ["Civil law", "International law", "Customary law", "Administrative law"], 1,
    "International law governs relationships between countries — the Bakassi dispute is a classic example."),
  Q("gst112_t3_q6", T3, "Sharia law is an example of:",
    ["Criminal law", "Customary law", "Religious law", "Constitutional law"], 2,
    "Sharia is based on religion, making it a form of religious law."),
  Q("gst112_t3_q7", T3, "The highest court in Nigeria is the:",
    ["Court of Appeal", "Magistrate Court", "Supreme Court", "Customary Court"], 2,
    "The hierarchy is: Supreme Court → Court of Appeal → High Court → Magistrate Court → Customary Court."),
  Q("gst112_t3_q8", T3, "Which of the following is NOT listed among Nigeria's fundamental human rights?",
    ["Right to life", "Right to freedom of religion", "Right to free internet access", "Right to education"], 2,
    "Constitutional fundamental rights include life, liberty, equality, expression, religion, education, work, property and fair trial — not free internet."),
  Q("gst112_t3_q9", T3, "Tort law primarily covers:",
    ["Crimes against the state", "Civil wrongs and compensation", "International treaties", "Traditional customs"], 1,
    "Tort law deals with civil wrongs and compensating victims for damages caused."),

  // --- Topic 4: Trade & Self-Reliance ---
  Q("gst112_t4_q1", T4, "The earliest form of trade was:",
    ["Barter", "Credit trade", "Export-import", "Currency-based trade"], 0,
    "Trade began with barter — exchanging goods for goods — before currency was adopted."),
  Q("gst112_t4_q2", T4, "Retail trade differs from wholesale trade in that retail involves:",
    ["Selling in large quantities to middlemen", "Selling small quantities to final consumers", "Cross-border transactions only", "Online-only sales"], 1,
    "Wholesale is bulk selling; retail sells smaller quantities directly to final consumers."),
  Q("gst112_t4_q3", T4, "If a country's imports exceed its exports over time, a likely consequence is:",
    ["Deflation", "Inflation", "Automatic surplus", "Elimination of trade"], 1,
    "Persistent trade deficits tend to weaken the currency and drive inflation."),
  Q("gst112_t4_q4", T4, "A major reason countries trade internationally is:",
    ["Identical resources in every country", "Uneven distribution of natural resources", "A surplus of identical skills globally", "Fixed currency exchange worldwide"], 1,
    "Resources, climates, industrial capacity and skills are unevenly distributed — countries trade to access what they lack."),
  Q("gst112_t4_q5", T4, "Self-reliance is best described as:",
    ["Total isolation from global trade", "Meeting one's needs without excessive dependence on others", "Exporting only raw materials", "Relying solely on foreign aid"], 1,
    "Self-reliance means meeting economic needs without excessive dependence — not total isolation."),
  Q("gst112_t4_q6", T4, "Which of these is NOT listed as a benefit of self-reliance?",
    ["Reduces dependence on imports", "Encourages innovation", "Eliminates the need for trade entirely", "Improves national security"], 2,
    "Self-reliance reduces dependence and promotes innovation but does not eliminate trade. No country is fully self-reliant."),
  Q("gst112_t4_q7", T4, "Which traditional market is located in Kano?",
    ["Onitsha Main Market", "Ariaria Market", "Kurmi Market", "Idumota Market"], 2,
    "Kurmi is in Kano. Onitsha Main is in Anambra, Ariaria in Abia, and Idumota in Lagos."),
  Q("gst112_t4_q8", T4, "'Igba-Boi' is the indigenous apprenticeship system associated with the:",
    ["Hausa", "Yoruba", "Igbo", "Fulani"], 2,
    "Igba-Boi is the Igbo apprenticeship system where apprentices train for years and are typically given startup capital to begin their own business."),
  Q("gst112_t4_q9", T4, "Which of these is a Nigerian government program for skills and employment?",
    ["NDE", "FIFA", "OPEC", "ECOWAS"], 0,
    "NDE (National Directorate of Employment) supports skill acquisition; others are international organisations."),
  Q("gst112_t4_q10", T4, "Which program supports graduates in developing entrepreneurial skills during national service?",
    ["NYSC SAED", "SMEDAN", "N-Power", "YouWin"], 0,
    "NYSC SAED (Skills Acquisition and Entrepreneurship Development) trains Corps members during the service year."),
  Q("gst112_t4_q11", T4, "A major challenge of skill acquisition in Nigeria's education system is:",
    ["Too few students graduate", "Education is too theory-heavy and doesn't prepare graduates for real work", "Too much hands-on training", "Oversupply of capital"], 1,
    "Theory-heavy curricula, lack of startup capital and poor program sustainability are key challenges."),

  // --- Topic 5: Hausa, Nupe, Kanuri & Fulani — quick-facts set ---
  Q("gst112_t5_q1", T5, "Bayajida is credited with:",
    ["Founding the Nupe Kingdom", "Founding the original Hausa states", "Leading the Fulani Jihad", "Founding the Kanem-Borno Empire"], 1,
    "Bayajida is credited with the conquest and founding of the original Hausa states."),
  Q("gst112_t5_q2", T5, "The 7 original Hausa states are collectively known as:",
    ["Banza Bokwai", "Hausa Bakwai", "Sokoto Seven", "Kano Seven"], 1,
    "Hausa Bakwai = the 7 original Hausa states. Banza Bokwai = the non-original 7."),
  Q("gst112_t5_q3", T5, "The non-original 7 Hausa states are called:",
    ["Hausa Bakwai", "Banza Bokwai", "Sokoto Bakwai", "Fulani Bokwai"], 1,
    "Banza Bokwai refers to the non-original seven Hausa states."),
  Q("gst112_t5_q4", T5, "The early-19th-century Jihad that transformed Hausa land into a theocratic state was led by:",
    ["Idris Alooma", "Usman Dan Fodio", "Tsoede", "Bayajida"], 1,
    "Usman Dan Fodio led the early 19th-century Jihad; Sokoto became the caliphate's headquarters."),
  Q("gst112_t5_q5", T5, "Which of the following IS a Kanuri dialect?",
    ["Hausa", "Manga", "Yoruba", "Fulfulde"], 1,
    "Kanuri dialects include Manga, Tumari and Bilma. Hausa is a separate language, not a Kanuri dialect."),
  Q("gst112_t5_q6", T5, "The Kisra legend traces Kanuri origins to:",
    ["A Fulani missionary", "A prince from eastern Africa", "A Yoruba trader", "A Berber scholar"], 1,
    "According to the Kisra legend, Kanuri origins trace back to a prince from eastern Africa."),
  Q("gst112_t5_q7", T5, "Great leaders of the Kanem-Borno Empire included:",
    ["Usman Dan Fodio and Tsoede", "Ali Ghaji and Idris Alooma", "Bayajida and Sarki", "Ayegba Om'Idoko and Edegi"], 1,
    "Ali Ghaji and Idris Alooma are remembered as among the greatest Kanem-Borno rulers."),
  Q("gst112_t5_q8", T5, "The Fulani call themselves:",
    ["Sarki", "Fulbe", "Bornu", "Igbira"], 1,
    "The Fulani refer to themselves as Fulbe."),
  Q("gst112_t5_q9", T5, "Tsoede used which material to signify his authority?",
    ["Iron", "Bronze", "Gold", "Ivory"], 1,
    "Tsoede used bronze objects to signify his authority as founder of the Nupe Kingdom."),
  Q("gst112_t5_q10", T5, "In Fulani society, which role was traditionally associated with Fulani females?",
    ["Warfare", "Cow-milking", "Long-distance trade", "Blacksmithing"], 1,
    "Fulani females were traditionally engaged in cow-milking."),
  Q("gst112_t5_q11", T5, "Bornu is described as the first ethnic group in Northern Nigeria to embrace:",
    ["Christianity", "Hinduism", "Islam in West Africa", "Traditional religion"], 2,
    "Bornu (Kanuri) was the first ethnic group in Northern Nigeria to embrace Islam in West Africa."),

  // --- Topic 1 (extras): Ethnic Groups & Culture ---
  Q("gst112_t1_q23", T1, "Material culture refers to:",
    ["Religion and values", "Songs and dances only", "Physical objects a people create and use", "Abstract beliefs"], 2,
    "Material culture = the tangible things a people make (tools, buildings, clothing, art). Non-material culture = abstract things like beliefs and values."),
  Q("gst112_t1_q24", T1, "Which of these best describes the Igbo political structure?",
    ["Centralised kingdom", "Sultanate", "Republican / decentralised village democracy", "Feudal"], 2,
    "The Igbo traditionally practised a decentralised, village-based democratic system with councils of elders — no single king."),
  Q("gst112_t1_q25", T1, "Ahiajoku in Igbo tradition is the deity of:",
    ["Thunder", "The earth", "Yam/agriculture", "Rivers"], 2,
    "Ahiajoku is the Igbo deity of agriculture, particularly yam — a central food crop."),
  Q("gst112_t1_q26", T1, "Which Yoruba kingdom is traditionally regarded as the cradle of the Yoruba people?",
    ["Oyo", "Ibadan", "Ile-Ife", "Ilorin"], 2,
    "Ile-Ife is regarded as the ancestral home of the Yoruba; Oduduwa is the mythical progenitor."),
  Q("gst112_t1_q27", T1, "In Yoruba tradition, the mythical ancestor of the Yoruba is:",
    ["Oranmiyan", "Oduduwa", "Sango", "Obatala"], 1,
    "Oduduwa is recognised as the progenitor of the Yoruba nation."),
  Q("gst112_t1_q28", T1, "The Nupe Kingdom's traditional capital is:",
    ["Kano", "Bida", "Lokoja", "Ilorin"], 1,
    "Bida is the traditional headquarters of the Nupe Kingdom."),
  Q("gst112_t1_q29", T1, "The Igala Kingdom's traditional headquarters is:",
    ["Idah", "Lokoja", "Makurdi", "Otukpo"], 0,
    "Idah is the traditional seat of the Attah of Igala."),
  Q("gst112_t1_q30", T1, "Nshor festival of the Birom is primarily a:",
    ["Rain festival", "Fishing festival", "Hunting festival", "Harvest festival"], 2,
    "Mandyang is the Birom rain festival; Nshor is the hunting festival."),
  Q("gst112_t1_q31", T1, "The Tiv migrated into present-day Nigeria in roughly:",
    ["Four waves between 1475 and 1900", "One wave during 1914", "Two waves in the 20th century", "Five waves before 1000 AD"], 0,
    "Historical records describe four waves of Tiv migration from the Cameroon-Obudu Plateau between 1475 and 1900."),
  Q("gst112_t1_q32", T1, "Which of the following is NOT among the three largest ethnic groups in Nigeria?",
    ["Hausa", "Yoruba", "Igbo", "Tiv"], 3,
    "Hausa, Yoruba and Igbo are the three largest. Tiv, though significant, is not in the top three."),
  Q("gst112_t1_q33", T1, "Which is an example of material culture?",
    ["Folktales", "Religious beliefs", "Pottery and sculpture", "Marriage customs"], 2,
    "Pottery and sculpture are physical artefacts, therefore material culture."),
  Q("gst112_t1_q34", T1, "A major factor that has helped Nigerian languages survive globalisation is:",
    ["Banning foreign languages", "Use of indigenous languages in Nollywood and music", "Replacing native names", "Closing cultural centres"], 1,
    "The heavy use of Yoruba, Igbo, Hausa and Pidgin in Nollywood films and Afrobeats has helped preserve and project Nigerian languages."),
  Q("gst112_t1_q35", T1, "Which of the following is a PURPOSE of culture?",
    ["Division and discrimination", "Identity and social cohesion", "Economic collapse", "Erasure of values"], 1,
    "Culture gives a people identity, values, cohesion and a sense of belonging."),

  // --- Topic 2 (extras): Amalgamation of 1914 ---
  Q("gst112_t2_q11", T2, "Which statement best describes pre-1914 Nigeria?",
    ["One unified political entity", "A collection of independent kingdoms and societies", "A Portuguese colony", "A French protectorate"], 1,
    "Before 1914 the area was made up of independent kingdoms, emirates and stateless societies — not a single political unit."),
  Q("gst112_t2_q12", T2, "A political motivation for amalgamation was Britain's desire to:",
    ["Give Nigerians independence immediately", "Simplify administration by uniting Northern and Southern Protectorates", "Abolish the emirate system", "Install a democratic parliament"], 1,
    "Britain saw administrative simplification and cost savings in combining the two protectorates under one Governor-General."),
  Q("gst112_t2_q13", T2, "Indirect Rule worked MOST successfully in which region?",
    ["Southwest", "Southeast", "North", "Niger Delta"], 2,
    "The established emirate structure in the North fit Indirect Rule almost perfectly; in the Southeast, no similar hierarchy existed."),
  Q("gst112_t2_q14", T2, "A POSITIVE legacy of amalgamation is:",
    ["Intensified ethnic rivalry", "Creation of one large Nigerian state and economic integration", "Loss of traditional authority", "Collapse of education"], 1,
    "Amalgamation unified diverse peoples under one state and enabled integrated infrastructure and economy."),
  Q("gst112_t2_q15", T2, "A NEGATIVE legacy of amalgamation was:",
    ["Unified currency", "Shared infrastructure", "Heightened ethnic tensions and regional imbalance", "Adoption of English"], 2,
    "Joining culturally distinct regions without adequate integration planning fuelled ethnic rivalry and uneven development."),
  Q("gst112_t2_q16", T2, "The NCNC political party was primarily associated with which region?",
    ["North", "West", "East", "Middle Belt"], 2,
    "NCNC (National Council of Nigeria and the Cameroons) was largely Eastern-based; NPC was Northern and Action Group Western."),
  Q("gst112_t2_q17", T2, "Which constitution granted regional autonomy in Nigeria?",
    ["Clifford 1922", "Richards 1946", "Macpherson 1951", "Lyttleton 1954"], 3,
    "The Lyttleton Constitution of 1954 introduced a federal system with significant regional autonomy."),
  Q("gst112_t2_q18", T2, "Britain imposed 'Warrant Chiefs' mainly in:",
    ["Northern emirates", "Southern areas without kings (e.g. among the Igbo)", "Lagos Colony", "Kanem-Borno"], 1,
    "In the south-east, Britain appointed artificial 'Warrant Chiefs' because the Igbo had no traditional kings, leading to resentment and protests."),

  // --- Topic 3 (extras): Social Justice & Law ---
  Q("gst112_t3_q10", T3, "Civil law primarily deals with:",
    ["Crimes against the state", "Disputes between private individuals (contracts, property, family)", "International treaties", "Religious rulings"], 1,
    "Civil law handles private disputes — contracts, property, family — with remedies like damages, rather than imprisonment."),
  Q("gst112_t3_q11", T3, "Customary law in Nigeria primarily refers to:",
    ["English common law", "Rules based on local traditions and customs", "Sharia law only", "International conventions"], 1,
    "Customary law is unwritten law derived from the customs of a community, recognised where not repugnant to natural justice."),
  Q("gst112_t3_q12", T3, "Which right guarantees that no one can be jailed without a fair trial?",
    ["Right to life", "Right to personal liberty and fair hearing", "Right to movement", "Right to property"], 1,
    "Liberty and fair hearing protect individuals from arbitrary detention and ensure due process in court."),
  Q("gst112_t3_q13", T3, "Equity (as a pillar of social justice) means:",
    ["Treating everyone identically regardless of need", "Giving each person what they need for fair outcomes", "Only helping the rich", "Ignoring fairness"], 1,
    "Equity recognises that different people have different needs; fair outcomes may require different levels of support."),
  Q("gst112_t3_q14", T3, "Which branch of government makes laws in Nigeria?",
    ["Executive", "Judiciary", "Legislature (National/State Assemblies)", "Traditional rulers"], 2,
    "The legislature (National Assembly federally, State Assemblies at state level) is responsible for law-making."),
  Q("gst112_t3_q15", T3, "The rule of law means:",
    ["The president is above the law", "No one is above the law; laws apply to all equally", "Only police obey the law", "Laws change every year"], 1,
    "Rule of law = everyone, including government officials, is subject to the law."),

  // --- Topic 4 (extras): Trade & Self-Reliance ---
  Q("gst112_t4_q12", T4, "Which of these is NOT a traditional Nigerian market mentioned in the notes?",
    ["Kurmi Market", "Onitsha Main Market", "Ariaria Market", "Times Square Market"], 3,
    "Times Square is in New York. Kurmi, Onitsha Main, Ariaria and Idumota are major Nigerian markets."),
  Q("gst112_t4_q13", T4, "Aba is particularly known for:",
    ["Cocoa processing", "Leatherwork and garment manufacturing", "Oil refining", "Salt mining"], 1,
    "Aba is famous for leather goods and garment production; Ariaria Market is one of the largest in West Africa."),
  Q("gst112_t4_q14", T4, "Which agency specifically supports small and medium enterprises in Nigeria?",
    ["SMEDAN", "NYSC", "FRSC", "NAFDAC"], 0,
    "SMEDAN = Small and Medium Enterprises Development Agency of Nigeria."),
  Q("gst112_t4_q15", T4, "The Igba-Boi apprenticeship system helps reduce:",
    ["Crime rates only", "Unemployment and builds wealth within communities", "Foreign exchange", "Taxation"], 1,
    "Igba-Boi trains apprentices who are later given startup capital, reducing unemployment and spreading entrepreneurship."),
  Q("gst112_t4_q16", T4, "Internal trade can be classified into:",
    ["Retail and wholesale", "Export and import only", "Barter only", "Services and goods internationally"], 0,
    "Internal (domestic) trade is divided into wholesale (bulk) and retail (small-quantity to final consumer)."),
  Q("gst112_t4_q17", T4, "Why do governments often encourage local production of essential goods?",
    ["To increase imports", "To reduce dependence on foreign countries and build self-reliance", "To cut taxes for foreign firms", "To raise global prices"], 1,
    "Local production creates jobs, saves foreign exchange and promotes national self-reliance."),
  Q("gst112_t4_q18", T4, "A key consequence of over-dependence on imports for a nation's economy is:",
    ["A strong currency", "Weakened currency and loss of local jobs", "Higher exports automatically", "Economic stability"], 1,
    "Over-dependence on imports weakens the local currency and crowds out domestic producers and jobs."),

  // --- Topic 5 (extras): Hausa, Nupe, Kanuri & Fulani ---
  Q("gst112_t5_q12", T5, "The Hausa Bakwai states include:",
    ["Daura, Kano, Katsina, Zaria, Gobir, Rano, Biram", "Oyo, Benin, Ife, Warri, Lagos, Abeokuta, Ilorin", "Sokoto, Gwandu, Borno, Kanem, Agades, Ilorin, Nupe", "Kebbi, Zamfara, Nupe, Ilorin, Yauri, Gwari, Kwararafa"], 0,
    "The 7 original Hausa states are Daura, Kano, Katsina, Zaria (Zazzau), Gobir, Rano and Biram."),
  Q("gst112_t5_q13", T5, "Sokoto became the headquarters of which entity after the 1804 jihad?",
    ["Kanem-Borno Empire", "Sokoto Caliphate", "Nupe Kingdom", "Igala Kingdom"], 1,
    "After Usman Dan Fodio's 1804 jihad, Sokoto was established as the headquarters of the Sokoto Caliphate."),
  Q("gst112_t5_q14", T5, "The Fulani Gida are distinguished from Fulani Bororo in that they:",
    ["Rear cattle nomadically", "Are town-dwelling traders and craftsmen", "Are nomadic herdsmen only", "Live only in Niger Republic"], 1,
    "Fulani Gida are settled town dwellers engaged in trade, crafts and Islamic scholarship. Fulani Bororo are nomadic cattle rearers."),
  Q("gst112_t5_q15", T5, "Which Kanem-Borno ruler is especially remembered for military and administrative reforms?",
    ["Usman Dan Fodio", "Idris Alooma", "Tsoede", "Bayajida"], 1,
    "Mai Idris Alooma is regarded as one of the greatest Kanem-Borno rulers, renowned for military and administrative reforms."),
  Q("gst112_t5_q16", T5, "A common traditional occupation of the Nupe is:",
    ["Camel herding only", "Fishing, farming and bronze/brass work", "Deep-sea trade only", "Salt mining"], 1,
    "The Nupe, along the Niger-Benue, are known for farming, fishing and their skilled bronze/brass work."),
  Q("gst112_t5_q17", T5, "Which language family does Hausa belong to?",
    ["Niger-Congo", "Afro-Asiatic", "Nilo-Saharan", "Indo-European"], 1,
    "Hausa is an Afro-Asiatic (Chadic) language."),
  Q("gst112_t5_q18", T5, "Which ethnic group's traditional title for its king is 'Attah'?",
    ["Igala", "Nupe", "Kanuri", "Fulani"], 0,
    "The Attah of Igala is the traditional ruler of the Igala Kingdom based at Idah."),
];

export const GST_112_SEED: Course = {
  id: "gst112",
  name: "GST 112 — Nigerian Peoples & Culture",
  description: "Practice Questions based on all the notes we've had this semester",
  createdAt: Date.now(),
  updatedAt: Date.now(),
  questions,
};
