import type { Course, Question } from "../types";

const Q = (
  id: string,
  topic: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question => ({ id, type: "mcq", topic, question, options, correctIndex, explanation });

const T1 = "Introduction & Hydrological Cycle";
const T2 = "Data Collection";
const T3 = "Precipitation & Evapotranspiration";
const T4 = "Interception, Run-off, Infiltration & Drainage Basin";
const T5 = "Land Use & Climate Change";
const T6 = "IWRM & Water Management";
const T7 = "Water Quality";
const T8 = "Scarcity, Drought & Flooding";
const T9 = "Water Policy, Law & Governance";

const questions: Question[] = [
  // ---------- T1: Introduction & Hydrological Cycle ----------
  Q("hwm_t1_q1", T1, "________ is the science that studies water — where it comes from, how it moves, and how it is distributed on Earth.",
    ["Geology", "Hydrology", "Meteorology", "Oceanography"], 1,
    "Hydrology is defined as the science of water on Earth — its occurrence, movement and distribution."),
  Q("hwm_t1_q2", T1, "Hydrology is described as an ________ science because it borrows from physics, chemistry, biology, geology, mathematics and statistics.",
    ["isolated", "interdisciplinary", "applied-only", "observational-only"], 1,
    "Hydrology is interdisciplinary — drawing on many sciences."),
  Q("hwm_t1_q3", T1, "Water is the ________ natural resource on Earth.",
    ["smallest", "rarest", "largest", "most expensive"], 2,
    "The notes describe water as the largest natural resource on Earth."),
  Q("hwm_t1_q4", T1, "Pure water boils at ________ °C at standard atmospheric pressure.",
    ["50", "75", "100", "212"], 2,
    "Water boils at 100 °C and freezes at 0 °C."),
  Q("hwm_t1_q5", T1, "Water is referred to as a ________ solvent because it can dissolve a wide variety of substances.",
    ["weak", "universal", "polar-only", "temporary"], 1,
    "Water is called a universal solvent due to its ability to dissolve many substances."),
  Q("hwm_t1_q6", T1, "The hydrological cycle is powered mainly by the ________.",
    ["moon", "wind", "sun", "oceans"], 2,
    "The sun's energy drives evaporation, which is the engine of the water cycle."),
  Q("hwm_t1_q7", T1, "The total number of processes involved in the hydrological cycle according to the notes is ________.",
    ["5", "7", "9", "11"], 3,
    "The notes list 11 processes: precipitation, condensation, evaporation, evapotranspiration, run-off, groundwater, streamflow, infiltration, percolation, radioactive exchange and soil moisture."),
  Q("hwm_t1_q8", T1, "The process by which plants release water vapour into the atmosphere is called ________.",
    ["evaporation", "condensation", "transpiration", "precipitation"], 2,
    "Transpiration — plants release water vapour through stomata on their leaves."),
  Q("hwm_t1_q9", T1, "Plants use only about ________ of the water they absorb; the rest is released as water vapour.",
    ["1%", "10%", "50%", "99%"], 0,
    "About 1% of the water taken up is used by the plant; 99% is transpired."),
  Q("hwm_t1_q10", T1, "________ is the opposite of evaporation — water vapour cools and turns back into liquid.",
    ["Infiltration", "Condensation", "Precipitation", "Run-off"], 1,
    "Condensation is the reverse of evaporation."),
  Q("hwm_t1_q11", T1, "The world receives an average of about ________ mm of precipitation per year.",
    ["98", "480", "980", "1,980"], 2,
    "Global average annual precipitation is about 980 mm."),
  Q("hwm_t1_q12", T1, "Only about ________ of all Earth's water is fresh water.",
    ["3%", "13%", "30%", "50%"], 0,
    "About 3% of Earth's water is fresh; the rest is salty."),
  Q("hwm_t1_q13", T1, "About ________ of global evaporation comes from the oceans.",
    ["6%", "46%", "86%", "96%"], 2,
    "86% of global evaporation comes from oceans."),
  Q("hwm_t1_q14", T1, "Without the cooling effect of the hydrological cycle, Earth's surface temperature could rise by about ________ °C.",
    ["6.7", "16", "67", "167"], 2,
    "The notes state that without the cooling effect of the cycle, surface temperature could rise by 67 °C."),
  Q("hwm_t1_q15", T1, "A closed lake with no outlet, such as the ________, becomes salty over time because water leaves only by evaporation.",
    ["Lake Victoria", "Dead Sea", "Lake Chad", "River Niger"], 1,
    "The Dead Sea is a classic example of a closed (endorheic) lake that has become very salty."),
  Q("hwm_t1_q16", T1, "The water-balance formula from the notes is Q = P − E + ΔS, where ΔS represents the ________.",
    ["total precipitation", "change in storage", "evaporation rate", "outflow"], 1,
    "ΔS = change in storage in the water balance equation."),
  Q("hwm_t1_q17", T1, "In the formula Q = P − E + ΔS, all quantities are measured in ________.",
    ["cm", "mm", "m", "m³/s"], 1,
    "All quantities in this water-balance form are in mm."),
  Q("hwm_t1_q18", T1, "A warmer atmosphere holds more ________, which intensifies the hydrological cycle.",
    ["oxygen", "moisture", "carbon dioxide", "dust"], 1,
    "A warmer atmosphere can hold more moisture, which speeds up and intensifies the water cycle."),

  // ---------- T2: Data Collection ----------
  Q("hwm_t2_q1", T2, "Precipitation is most commonly measured using ________.",
    ["lysimeters", "rain gauges", "weirs", "flumes"], 1,
    "Rain gauges (including tipping-bucket gauges) are the primary instruments for measuring precipitation."),
  Q("hwm_t2_q2", T2, "Stream flow can be measured using weirs, flumes and ________.",
    ["rain gauges", "velocity meters", "lysimeters", "evaporation pans"], 1,
    "Stream flow is measured with weirs, flumes and velocity meters."),
  Q("hwm_t2_q3", T2, "Evaporation is measured using evaporation pans and ________.",
    ["weirs", "flumes", "lysimeters", "tipping-bucket gauges"], 2,
    "Evaporation/evapotranspiration is measured using evaporation pans and lysimeters."),
  Q("hwm_t2_q4", T2, "In site selection for data collection, the location must properly represent the ________.",
    ["country", "continent", "catchment area", "government boundary"], 2,
    "Sites should represent the catchment area so the data are meaningful."),
  Q("hwm_t2_q5", T2, "Digital ________ allow continuous recording of hydrological data.",
    ["telescopes", "data loggers", "barometers", "spectrometers"], 1,
    "Digital data loggers are used for continuous recording and storage of hydrological data."),
  Q("hwm_t2_q6", T2, "A Hydrological Information System consists of three parts: observation network, hydrological database and hydrological ________.",
    ["models", "satellites", "barometers", "surveyors"], 0,
    "The three parts are: observation network, hydrological database and hydrological models."),
  Q("hwm_t2_q7", T2, "A ________ curve links water stage (height) to discharge in a stream.",
    ["drainage", "rating", "stage", "infiltration"], 1,
    "Rating curves relate stage (water level) to discharge."),
  Q("hwm_t2_q8", T2, "The first step in data processing is ________ — a quality check of recorded data.",
    ["automation", "modelling", "validation", "publication"], 2,
    "Validation is the quality-control step in data processing."),
  Q("hwm_t2_q9", T2, "A major challenge for hydrological data collection in developing countries is ________.",
    ["too much funding", "excessive automation", "equipment damage and poor maintenance", "too many observers"], 2,
    "Floods damage equipment, and poor maintenance plus limited resources are key challenges."),

  // ---------- T3: Precipitation & Evapotranspiration ----------
  Q("hwm_t3_q1", T3, "Before it hits the ground, precipitation is a ________ concept; after it lands, it becomes a hydrological one.",
    ["geological", "meteorological", "biological", "astronomical"], 1,
    "While still falling, precipitation is meteorological; once it reaches the ground it becomes hydrological."),
  Q("hwm_t3_q2", T3, "Drizzle consists of tiny droplets between ________ mm in diameter.",
    ["0.01–0.05", "0.1–0.5", "0.5–1.0", "1.0–5.0"], 1,
    "Drizzle droplets range from about 0.1 to 0.5 mm."),
  Q("hwm_t3_q3", T3, "Rain is classified as ________ when the intensity is greater than 7.6 mm/hr.",
    ["light", "moderate", "heavy", "extreme"], 2,
    "Heavy rain: > 7.6 mm/hr. Light: up to 2 mm/hr. Moderate: 2.8–7.6 mm/hr."),
  Q("hwm_t3_q4", T3, "________ is clear, smooth ice formed by freezing rain on surfaces, with specific gravity 0.8–0.9.",
    ["Rime", "Glaze", "Snow", "Hail"], 1,
    "Glaze — clear, smooth, dense ice from freezing rain (SG 0.8–0.9)."),
  Q("hwm_t3_q5", T3, "________ is white, opaque, granular ice with specific gravity as low as 0.2–0.3.",
    ["Glaze", "Sleet", "Rime", "Hail"], 2,
    "Rime is white, opaque, granular ice (SG 0.2–0.3)."),
  Q("hwm_t3_q6", T3, "Snow has an average density assumed to be about ________.",
    ["0.01", "0.1", "0.5", "1.0"], 1,
    "Snow's average density is taken as ~0.1."),
  Q("hwm_t3_q7", T3, "Hailstones range from about ________ mm in diameter.",
    ["0.1–1", "1–5", "5–125", "100–500"], 2,
    "Hail: 5–125 mm, formed in cumulonimbus clouds."),
  Q("hwm_t3_q8", T3, "________ is formed by the refreezing of raindrops near Earth's surface.",
    ["Drizzle", "Sleet", "Dew", "Glaze"], 1,
    "Sleet forms when raindrops refreeze near the surface."),
  Q("hwm_t3_q9", T3, "Precipitation caused by air being forced up a mountain slope is called ________.",
    ["cyclonic", "convective", "orographic", "frontal"], 2,
    "Orographic precipitation results from moist air being lifted over mountains."),
  Q("hwm_t3_q10", T3, "Precipitation at the boundary between two air masses is called ________ (or frontal) precipitation.",
    ["convective", "cyclonic", "orographic", "tropical"], 1,
    "Cyclonic/frontal precipitation occurs at warm or cold fronts."),
  Q("hwm_t3_q11", T3, "Rain gauges are broadly divided into recording and ________ gauges.",
    ["tipping", "float", "non-recording", "weighing"], 2,
    "There are two broad classes: recording and non-recording gauges."),
  Q("hwm_t3_q12", T3, "A ________ rain gauge records each small fixed volume of rain as the bucket tips.",
    ["float", "tipping bucket", "weighing", "radar"], 1,
    "Tipping-bucket gauges record rainfall by counting tips of a calibrated bucket."),
  Q("hwm_t3_q13", T3, "The 5 types of recording gauges are tipping bucket, weighing, float, radar and ________.",
    ["satellite", "balloon", "optical", "lysimeter"], 0,
    "The five recording types given in the notes are tipping bucket, weighing, float, radar and satellite."),
  Q("hwm_t3_q14", T3, "________ combines evaporation from soils/water surfaces and transpiration from plants.",
    ["Interception", "Infiltration", "Evapotranspiration", "Percolation"], 2,
    "Evapotranspiration = evaporation + transpiration."),
  Q("hwm_t3_q15", T3, "Solar radiation, humidity, wind speed, sunshine duration and temperature are ________ factors affecting evapotranspiration.",
    ["non-climatic", "climatic", "geological", "biological"], 1,
    "These are climatic (weather) factors influencing evapotranspiration."),
  Q("hwm_t3_q16", T3, "Soil type, vegetation type and water depth are ________ factors influencing evapotranspiration.",
    ["climatic", "non-climatic", "meteorological", "astronomical"], 1,
    "These are non-climatic factors such as surface and soil characteristics."),

  // ---------- T4: Interception, Run-off, Infiltration & Drainage Basin ----------
  Q("hwm_t4_q1", T4, "________ is the portion of rainfall caught by vegetation before reaching the ground.",
    ["Run-off", "Interception", "Infiltration", "Percolation"], 1,
    "Interception is rainfall temporarily held by leaves, stems or branches."),
  Q("hwm_t4_q2", T4, "Water that drips through gaps in leaves to the ground is called ________.",
    ["stemflow", "throughfall", "run-off", "percolation"], 1,
    "Throughfall is rain that drips through gaps in the canopy."),
  Q("hwm_t4_q3", T4, "Water that runs down plant stems to the ground is called ________.",
    ["throughfall", "stemflow", "infiltration", "seepage"], 1,
    "Stemflow is water running down stems/trunks to the ground."),
  Q("hwm_t4_q4", T4, "________ is the water that flows over the land surface and collects in streams and rivers.",
    ["Infiltration", "Percolation", "Run-off", "Condensation"], 2,
    "Surface run-off is overland flow that enters streams and rivers."),
  Q("hwm_t4_q5", T4, "Groundwater run-off reaches channels slowly, after days or ________, by percolating through soil.",
    ["hours", "minutes", "weeks", "centuries"], 2,
    "Groundwater run-off reaches channels after days or weeks."),
  Q("hwm_t4_q6", T4, "Rainfall intensity, duration and distribution over a basin are ________ factors that affect run-off.",
    ["basin", "precipitation", "soil", "vegetation"], 1,
    "These are precipitation factors affecting run-off."),
  Q("hwm_t4_q7", T4, "Land use, soil type, basin shape and drainage type are ________ characteristics affecting run-off.",
    ["precipitation", "atmospheric", "basin", "climatic"], 2,
    "These are basin characteristics affecting run-off."),
  Q("hwm_t4_q8", T4, "________ is the process of water entering the soil through its surface.",
    ["Percolation", "Infiltration", "Interception", "Condensation"], 1,
    "Infiltration is water entering soil through its surface."),
  Q("hwm_t4_q9", T4, "________ is the movement of water downward through the soil toward the water table.",
    ["Infiltration", "Run-off", "Percolation", "Stemflow"], 2,
    "Percolation is the downward movement through the soil profile toward the water table."),
  Q("hwm_t4_q10", T4, "Infiltration proceeds in three stages: surface entry, movement through soil and ________.",
    ["increase of storage capacity", "reduction of the soil's storage capacity", "evaporation of pore water", "condensation of vapour"], 1,
    "The three stages are surface entry, movement through the soil and reduction of the soil's storage capacity."),
  Q("hwm_t4_q11", T4, "Infiltration capacity is the ________ rate at which soil can absorb water at any given time.",
    ["minimum", "average", "maximum", "zero"], 2,
    "Infiltration capacity is the maximum rate at which soil can absorb water at a given moment."),
  Q("hwm_t4_q12", T4, "Infiltration capacity is measured in ________.",
    ["cm/day", "mm", "m³/s", "litres"], 1,
    "Infiltration capacity is expressed in mm (per unit time) in the notes."),
  Q("hwm_t4_q13", T4, "A ________ infiltrometer is a field device used to determine infiltration rate.",
    ["single pan", "double ring", "tipping bucket", "weighing"], 1,
    "Double-ring infiltrometers are common; flooding and sprinkler types are also used."),
  Q("hwm_t4_q14", T4, "Holtan's 1961 equation is written F = a(S − f)ⁿ + ________.",
    ["fe", "fc", "fi", "ft"], 0,
    "Holtan 1961: F = a(S − f)ⁿ + fe."),
  Q("hwm_t4_q15", T4, "A ________ basin is any land area where all precipitation drains to a common outlet.",
    ["drainage", "climatic", "political", "aquifer"], 0,
    "A drainage basin (catchment/watershed) drains to one outlet such as a river or lake."),
  Q("hwm_t4_q16", T4, "A closed basin with no outlet is called a(n) ________ basin.",
    ["ocean", "river", "endorheic", "estuarine"], 2,
    "An endorheic basin has no outlet to the sea (e.g. the Dead Sea)."),
  Q("hwm_t4_q17", T4, "The ________ factor of a drainage basin concerns the physical properties of its soils.",
    ["geologic", "morphologic", "soil", "climatic"], 2,
    "Soil factors are about the physical properties of the soils in the basin."),
  Q("hwm_t4_q18", T4, "The ________ factor of a drainage basin concerns the underlying rock depth and structure.",
    ["morphologic", "vegetational", "geologic", "climatic"], 2,
    "Geologic factors describe underlying rock depth and structure."),

  // ---------- T5: Land Use & Climate Change ----------
  Q("hwm_t5_q1", T5, "________ refers to how humans use land (e.g. farming, cities), while land cover refers to what physically covers it.",
    ["Land cover", "Land use", "Land form", "Land tax"], 1,
    "Land use = how people use land; land cover = what physically covers it."),
  Q("hwm_t5_q2", T5, "Deforestation can increase sediment loads by about ________ times.",
    ["0.2–1", "2–10", "20–50", "100–200"], 1,
    "Clearing forests increases erosion and sediment yield by 2–10 times."),
  Q("hwm_t5_q3", T5, "In cleared Amazon areas, peak river flows have increased by about ________.",
    ["5–10%", "15–20%", "25–50%", "100–150%"], 2,
    "The Brazilian Amazon shows 25–50% higher peak flows after clearing."),
  Q("hwm_t5_q4", T5, "Agriculture uses about ________ of the world's freshwater.",
    ["10%", "30%", "50%", "70%"], 3,
    "Agriculture accounts for roughly 70% of global freshwater use."),
  Q("hwm_t5_q5", T5, "Urban areas can have ________ times higher peak floods than natural catchments.",
    ["2–10", "20–50", "50–100", "100–200"], 0,
    "Urbanisation produces 2–10× higher peak flood flows."),
  Q("hwm_t5_q6", T5, "Stream health begins to seriously decline once more than ________ of a catchment is impervious.",
    ["1–2%", "5–7%", "10–15%", "40–50%"], 2,
    "The classic impervious-cover threshold is 10–15%."),
  Q("hwm_t5_q7", T5, "The world has lost over ________ of its wetlands since 1970.",
    ["5%", "15%", "35%", "75%"], 2,
    "Over 35% of wetlands have been lost since 1970."),
  Q("hwm_t5_q8", T5, "The combination of more floods, less recharge and degraded streams in cities is called the ________.",
    ["urban heat effect", "urban stream syndrome", "karst effect", "peak-water effect"], 1,
    "The pattern is named the 'urban stream syndrome.'"),
  Q("hwm_t5_q9", T5, "Satellites such as ________ and Sentinel are widely used to detect land-cover change.",
    ["Hubble", "Landsat", "Voyager", "Chandra"], 1,
    "Landsat and Sentinel imagery are the workhorses of LULC remote sensing."),
  Q("hwm_t5_q10", T5, "________ and HEC-HMS are examples of hydrological models used to evaluate land-use effects.",
    ["SWAT", "AutoCAD", "MATLAB", "ArcGIS-only"], 0,
    "SWAT (Soil & Water Assessment Tool) and HEC-HMS are common hydrological models."),
  Q("hwm_t5_q11", T5, "Sea levels are projected to rise by about ________ m by 2100.",
    ["0.03–0.1", "0.3–1.0", "3–5", "10–15"], 1,
    "Projected sea-level rise is about 0.3–1.0 m by 2100."),
  Q("hwm_t5_q12", T5, "Glaciers have been losing roughly ________ billion tonnes of ice per year.",
    ["2.67", "26.7", "267", "2,670"], 2,
    "Global glacier mass loss is about 267 Gt/year."),
  Q("hwm_t5_q13", T5, "Snowpack in the western US has declined about ________ since 1950.",
    ["1–3%", "5–10%", "15–30%", "60–80%"], 2,
    "Western US snowpack has declined 15–30% since 1950."),
  Q("hwm_t5_q14", T5, "Lake ________ has lost about 90% of its surface area since the 1960s.",
    ["Victoria", "Chad", "Tanganyika", "Kainji"], 1,
    "Lake Chad has shrunk by about 90% since the 1960s."),
  Q("hwm_t5_q15", T5, "The 2010 ________ floods affected about 20 million people.",
    ["Pakistan", "Thailand", "Brazilian", "German"], 0,
    "The 2010 Pakistan floods displaced roughly 20 million people."),
  Q("hwm_t5_q16", T5, "'________ water' describes the short-term increase in river flow from melting glaciers before supply declines.",
    ["Grey", "Peak", "Dead", "Blue"], 1,
    "The 'peak water' phenomenon is the temporary glacier-melt bonus before long-term decline."),
  Q("hwm_t5_q17", T5, "Melting ________ can release mercury into water systems.",
    ["permafrost", "coral", "coal", "bauxite"], 0,
    "Thawing permafrost can release mercury and other contaminants."),
  Q("hwm_t5_q18", T5, "Artificially refilling aquifers during wet seasons is called ________.",
    ["Managed Aquifer Recharge (MAR)", "Managed Surface Release", "Interbasin Transfer", "Desalination"], 0,
    "MAR = Managed Aquifer Recharge."),

  // ---------- T6: IWRM & Water Management ----------
  Q("hwm_t6_q1", T6, "IWRM stands for Integrated Water ________ Management.",
    ["Resources", "Recycling", "Regulation", "Reservoir"], 0,
    "IWRM = Integrated Water Resources Management."),
  Q("hwm_t6_q2", T6, "IWRM came from the 1992 ________ Conference.",
    ["Stockholm", "Dublin", "Rio", "Paris"], 1,
    "The Dublin Conference of 1992 produced the four Dublin Principles."),
  Q("hwm_t6_q3", T6, "The first Dublin Principle states that freshwater is a finite and ________ resource.",
    ["infinite", "renewable", "vulnerable", "replaceable"], 2,
    "Principle 1: freshwater is a finite and vulnerable resource."),
  Q("hwm_t6_q4", T6, "The Dublin Principles recognise that ________ play a central role in water management.",
    ["only men", "women", "only engineers", "politicians only"], 1,
    "Principle 3 emphasises the central role of women in water."),
  Q("hwm_t6_q5", T6, "The fourth Dublin Principle recognises water as an ________ good.",
    ["ecological", "educational", "economic", "expendable"], 2,
    "Principle 4: water has economic value and should be treated as an economic good — while protecting basic access."),
  Q("hwm_t6_q6", T6, "The three core components of IWRM are enabling environment, institutional roles and management ________.",
    ["instruments", "indicators", "investments", "inventories"], 0,
    "The third component is management instruments — tools such as pricing, education and licensing."),
  Q("hwm_t6_q7", T6, "The best unit for IWRM is the ________ because water doesn't follow political borders.",
    ["country", "district", "river basin", "continent"], 2,
    "River basins are the preferred IWRM management unit."),
  Q("hwm_t6_q8", T6, "IWRM most directly supports ________.",
    ["SDG 1", "SDG 3", "SDG 6", "SDG 13"], 2,
    "SDG 6 (clean water and sanitation) is the main one; IWRM also supports others."),
  Q("hwm_t6_q9", T6, "Installing water meters alone can reduce water use by about ________.",
    ["1–3%", "15–30%", "50–60%", "70–80%"], 1,
    "Metering typically cuts demand by 15–30%."),
  Q("hwm_t6_q10", T6, "In many developing cities, ________ of water is lost before it reaches consumers.",
    ["3–5%", "10–15%", "30–50%", "80–90%"], 2,
    "Leakage losses can be 30–50% in many systems."),
  Q("hwm_t6_q11", T6, "________ irrigation can reduce agricultural water use by 40–70% compared with flood irrigation.",
    ["Flood", "Sprinkler", "Drip", "Basin"], 2,
    "Drip irrigation is the most water-efficient method mentioned."),
  Q("hwm_t6_q12", T6, "Giving crops slightly less water at non-critical growth stages is called ________ irrigation.",
    ["flood", "full", "deficit", "constant"], 2,
    "Deficit irrigation strategically withholds some water with minimal yield loss."),
  Q("hwm_t6_q13", T6, "China's South-North Water Transfer Project is an example of a(n) ________.",
    ["desalination plant", "interbasin transfer", "aquifer recharge project", "flood levee"], 1,
    "It is a large interbasin transfer scheme."),
  Q("hwm_t6_q14", T6, "________ is the process of removing salt from seawater to produce fresh water.",
    ["Distillation", "Desalination", "Chlorination", "Flocculation"], 1,
    "Desalination is the main alternative water source in coastal arid regions."),
  Q("hwm_t6_q15", T6, "Collecting water from sinks and showers for toilets and gardens is called ________ reuse.",
    ["blackwater", "greywater", "stormwater", "surfacewater"], 1,
    "Greywater = relatively clean wastewater from sinks/showers."),

  // ---------- T7: Water Quality ----------
  Q("hwm_t7_q1", T7, "Temperature, turbidity, colour and odour are ________ water-quality parameters.",
    ["chemical", "physical", "biological", "radiological"], 1,
    "These are physical parameters."),
  Q("hwm_t7_q2", T7, "pH, heavy metals and nitrates are ________ water-quality parameters.",
    ["physical", "chemical (inorganic)", "microbiological", "radiological"], 1,
    "pH, heavy metals and nitrates are inorganic chemical parameters."),
  Q("hwm_t7_q3", T7, "BOD, COD and pesticides are ________ water-quality parameters.",
    ["physical", "chemical (organic)", "radiological", "physical-only"], 1,
    "These are organic chemical parameters."),
  Q("hwm_t7_q4", T7, "E. coli, Cryptosporidium and viruses are ________ water-quality parameters.",
    ["physical", "chemical", "microbiological", "radiological"], 2,
    "These are microbiological parameters and cause most waterborne disease."),
  Q("hwm_t7_q5", T7, "Radon and uranium in water are ________ parameters.",
    ["physical", "chemical", "microbiological", "radiological"], 3,
    "These are radiological parameters with long-term health risks."),
  Q("hwm_t7_q6", T7, "A single identifiable outlet (such as a factory pipe) is a ________ source of pollution.",
    ["non-point", "point", "atmospheric", "natural"], 1,
    "Point sources are individual, identifiable outlets — easier to regulate."),
  Q("hwm_t7_q7", T7, "Pollution spread over a wide area (e.g. agricultural run-off) is a ________ source.",
    ["point", "non-point", "natural", "industrial"], 1,
    "Non-point sources are diffuse and harder to control."),
  Q("hwm_t7_q8", T7, "________ strips along stream banks are used to reduce pollution reaching water bodies.",
    ["Asphalt", "Buffer", "Concrete", "Iron"], 1,
    "Buffer strips trap sediments and nutrients before they reach streams."),
  Q("hwm_t7_q9", T7, "Drinking-water treatment typically includes coagulation, filtration and ________.",
    ["fermentation", "disinfection", "distillation", "centrifugation"], 1,
    "The classic steps are coagulation, filtration and disinfection."),
  Q("hwm_t7_q10", T7, "A ________ is a natural treatment system that uses wetlands built for water purification.",
    ["dry dam", "constructed wetland", "sand dune", "flood bank"], 1,
    "Constructed wetlands are engineered natural-treatment systems."),
  Q("hwm_t7_q11", T7, "TMDL (Total Maximum Daily ________) caps the pollution a water body can receive.",
    ["Level", "Load", "Leakage", "Limit"], 1,
    "TMDL = Total Maximum Daily Load."),
  Q("hwm_t7_q12", T7, "PFAS are often called '________' chemicals because of their extreme persistence.",
    ["sunset", "forever", "seasonal", "temporary"], 1,
    "PFAS are nicknamed 'forever chemicals' because they degrade very slowly."),

  // ---------- T8: Scarcity, Drought & Flooding ----------
  Q("hwm_t8_q1", T8, "When there is simply not enough water even with efficient use, it is called ________ scarcity.",
    ["economic", "physical", "institutional", "cultural"], 1,
    "Physical scarcity = not enough water exists."),
  Q("hwm_t8_q2", T8, "When water exists but people cannot afford infrastructure to access it, it is ________ scarcity.",
    ["physical", "economic", "institutional", "seasonal"], 1,
    "Economic scarcity = the resource is there but affordability/infrastructure is lacking."),
  Q("hwm_t8_q3", T8, "When governance, politics or law prevents access to water, it is ________ scarcity.",
    ["economic", "physical", "institutional", "religious"], 2,
    "Institutional scarcity is driven by governance/legal barriers."),
  Q("hwm_t8_q4", T8, "Using the Falkenmark Indicator, less than ________ m³/person/year is classed as absolute scarcity.",
    ["50", "500", "1,000", "1,700"], 1,
    "Below 500 m³/person/year = absolute scarcity."),
  Q("hwm_t8_q5", T8, "Between 1,000 and 1,700 m³/person/year is classed as ________.",
    ["no stress", "stressed", "scarce", "absolute scarcity"], 1,
    "1,000–1,700 m³/person/year indicates water stress."),
  Q("hwm_t8_q6", T8, "A shortage of rainfall compared with normal is ________ drought.",
    ["agricultural", "meteorological", "hydrological", "socio-economic"], 1,
    "Meteorological drought starts the chain — it's the rainfall deficit."),
  Q("hwm_t8_q7", T8, "Low soil moisture that prevents proper crop growth is ________ drought.",
    ["meteorological", "agricultural", "hydrological", "socio-economic"], 1,
    "Agricultural drought is when soil moisture drops below levels crops need."),
  Q("hwm_t8_q8", T8, "Rivers, reservoirs and lakes falling below normal levels defines ________ drought.",
    ["meteorological", "agricultural", "hydrological", "socio-economic"], 2,
    "Hydrological drought shows up in river, reservoir and lake levels."),
  Q("hwm_t8_q9", T8, "A drought that damages the economy and public health is described as ________.",
    ["meteorological", "agricultural", "hydrological", "socio-economic"], 3,
    "Socio-economic drought is drought's impact on people and economy."),
  Q("hwm_t8_q10", T8, "SPI stands for Standardised ________ Index.",
    ["Precipitation", "Pollution", "Pressure", "Peak"], 0,
    "SPI = Standardised Precipitation Index."),
  Q("hwm_t8_q11", T8, "PDSI stands for ________ Drought Severity Index.",
    ["Peak", "Palmer", "Pacific", "Planetary"], 1,
    "PDSI = Palmer Drought Severity Index."),
  Q("hwm_t8_q12", T8, "The ________ satellite mission is used to monitor changes in groundwater storage.",
    ["GRACE", "GPS", "GOES", "MODIS"], 0,
    "GRACE satellites measure gravity anomalies that reveal groundwater changes."),
  Q("hwm_t8_q13", T8, "A sudden, extremely fast flood in small, steep areas is a(n) ________ flood.",
    ["river", "flash", "coastal", "groundwater"], 1,
    "Flash floods occur in small steep catchments with very little warning time."),
  Q("hwm_t8_q14", T8, "Flooding caused by heavy rain overwhelming city drains is called ________ or pluvial flooding.",
    ["fluvial", "surface", "coastal", "dam-break"], 1,
    "Surface (pluvial) flooding is rain-driven urban flooding before water reaches rivers."),
  Q("hwm_t8_q15", T8, "Flooding caused by storm surges pushing seawater inland is ________ flooding.",
    ["groundwater", "surface", "coastal", "flash"], 2,
    "Coastal flooding is surge-driven and worsened by sea-level rise."),
  Q("hwm_t8_q16", T8, "Rising water tables emerging from below cause ________ flooding, which is slow but long-lasting.",
    ["river", "flash", "groundwater", "pluvial"], 2,
    "Groundwater flooding is driven by high water tables."),
  Q("hwm_t8_q17", T8, "Flood risk is expressed as Hazard × Exposure × ________.",
    ["Intensity", "Vulnerability", "Duration", "Velocity"], 1,
    "Flood risk = Hazard × Exposure × Vulnerability."),
  Q("hwm_t8_q18", T8, "Levees, retention basins and channel dredging are ________ flood-risk measures.",
    ["non-structural", "structural", "legal", "cultural"], 1,
    "These are structural (engineering) measures."),
  Q("hwm_t8_q19", T8, "Zoning laws and building codes are ________ flood-risk measures.",
    ["structural", "non-structural", "natural", "mechanical"], 1,
    "Planning and policy tools are non-structural measures."),
  Q("hwm_t8_q20", T8, "Green roofs, permeable pavements, bioswales and rain gardens are grouped under ________.",
    ["SUDS", "TMDL", "IWRM", "MAR"], 0,
    "SUDS = Sustainable Urban Drainage Systems."),

  // ---------- T9: Water Policy, Law & Governance ----------
  Q("hwm_t9_q1", T9, "In a national water policy, basic ________ needs come first in allocation priorities.",
    ["industrial", "human", "agricultural", "recreational"], 1,
    "Priority order: basic human needs → ecological flows → economic uses."),
  Q("hwm_t9_q2", T9, "The first global water conference was the ________ 1977 Mar del Plata Plan.",
    ["UNESCO", "UN", "WMO", "FAO"], 1,
    "The UN 1977 Mar del Plata conference was the first major global water meeting."),
  Q("hwm_t9_q3", T9, "The 1992 Dublin Principles form the foundation of ________.",
    ["SDG 6", "IWRM", "TMDL", "MAR"], 1,
    "The Dublin Principles underpin Integrated Water Resources Management."),
  Q("hwm_t9_q4", T9, "The 2000 MDGs targeted halving the number of people without safe water by ________.",
    ["2010", "2015", "2020", "2030"], 1,
    "MDG target year was 2015."),
  Q("hwm_t9_q5", T9, "SDG 6 aims for universal safe water and sanitation by ________.",
    ["2020", "2025", "2030", "2050"], 2,
    "SDG 6 has a 2030 target date."),
  Q("hwm_t9_q6", T9, "UN Resolution 64/292 (2010) recognised water and sanitation as a ________.",
    ["privilege", "human right", "commodity", "luxury"], 1,
    "UN 64/292 explicitly recognised water and sanitation as a human right."),
  Q("hwm_t9_q7", T9, "A legal permission to take a specified amount of water from a specified source is a water-use ________.",
    ["permit-only", "licence", "pension", "passport"], 1,
    "Water-use licences are the main legal instrument for abstraction control."),
  Q("hwm_t9_q8", T9, "A ________ permit is legal permission to release wastewater, subject to pollution limits.",
    ["discharge", "arrival", "transport", "storage"], 0,
    "Discharge permits govern releases of wastewater."),
  Q("hwm_t9_q9", T9, "The minimum water that must remain in a river for ecosystem health is the ________ flow requirement.",
    ["peak", "environmental", "return", "maximum"], 1,
    "Environmental (ecological) flows protect riverine ecosystems."),
  Q("hwm_t9_q10", T9, "South Africa's ________ National Water Act (1998) is regarded as a global model for ecological and basic human-need priorities.",
    ["SAT", "NWA", "SANRAL", "SAHRC"], 1,
    "South Africa's National Water Act (1998) is often cited as a leading example."),
  Q("hwm_t9_q11", T9, "Under ________ rights, only landowners next to a water body can use it.",
    ["prior-appropriation", "riparian", "public-trust", "administrative"], 1,
    "Riparian rights tie water use to owning land adjacent to a water body."),
  Q("hwm_t9_q12", T9, "'First in time, first in right' is the principle of ________ rights.",
    ["riparian", "prior appropriation", "public trust", "state ownership"], 1,
    "Prior appropriation gives earliest users the strongest rights."),
  Q("hwm_t9_q13", T9, "The ________ Doctrine holds that the state holds water in trust for all citizens.",
    ["Prior Appropriation", "Riparian", "Public Trust", "Upstream"], 2,
    "The Public Trust Doctrine puts private rights secondary to public interest."),
  Q("hwm_t9_q14", T9, "In most of Africa, China and South Africa, government owns the water and issues licences — this is ________ allocation.",
    ["Riparian", "Public Trust", "Prior Appropriation", "State ownership / administrative"], 3,
    "Administrative / state-ownership allocation is most flexible but depends on governance strength."),
  Q("hwm_t9_q15", T9, "There are about ________ river basins shared between two or more countries.",
    ["31", "131", "310", "1,310"], 2,
    "The notes cite approximately 310 transboundary river basins."),
  Q("hwm_t9_q16", T9, "The main international legal framework for shared rivers is the UN ________ Convention (1997).",
    ["Waterways", "Watercourses", "Aquifer", "Hydrology"], 1,
    "UN Watercourses Convention 1997."),
  Q("hwm_t9_q17", T9, "The Grand Ethiopian Renaissance Dam concerns the ________ basin.",
    ["Niger", "Nile", "Congo", "Limpopo"], 1,
    "GERD is on the Blue Nile — a dispute among Ethiopia, Sudan and Egypt."),
  Q("hwm_t9_q18", T9, "Under the human right to water, every person is entitled to about ________ litres per day.",
    ["5–10", "15–20", "50–100", "500–1,000"], 2,
    "The 50–100 L/day range is cited as sufficient."),
  Q("hwm_t9_q19", T9, "Water should be physically accessible within about ________ metres or 30 minutes.",
    ["100", "1,000", "5,000", "10,000"], 1,
    "Accessibility standard: within 1,000 m or 30 minutes."),
  Q("hwm_t9_q20", T9, "Water should be affordable — not more than ________ of household income.",
    ["0.5%", "3–5%", "15–20%", "50%"], 1,
    "Affordability threshold: no more than 3–5% of household income."),
  Q("hwm_t9_q21", T9, "Examples of River Basin Organisations include the Mekong River Commission, the Rhine Commission and the ________ Basin Authority.",
    ["Amazon", "Niger", "Thames", "Volga"], 1,
    "The Niger Basin Authority is the notes' African RBO example."),
];

export const HWM_SEED: Course = {
  id: "hwm",
  name: "HWM — Hydrology & Water Management",
  description: "Hwm practice questions based on all the notes we've had this semester",
  createdAt: Date.now(),
  updatedAt: Date.now(),
  questions,
};
